In [8]:
# @title
from IPython.display import display, HTML

display(HTML("""
<script>
const firstCell = document.querySelector('.cell.code_cell');
if (firstCell) {
  firstCell.querySelector('.input').style.pointerEvents = 'none';
  firstCell.querySelector('.input').style.opacity = '0.5';
}
</script>
"""))

html = """
<div style="display:flex; flex-direction:column; align-items:center; text-align:center; gap:12px; padding:8px;">
  <h1 style="margin:0;">👋 Welcome to <span style="color:#1E88E5;">Algopath Coding Academy</span>!</h1>

  <img src="https://raw.githubusercontent.com/sshariqali/mnist_pretrained_model/main/algopath_logo.jpg"
       alt="Algopath Coding Academy Logo"
       width="400"
       style="border-radius:15px; box-shadow:0 4px 12px rgba(0,0,0,0.2); max-width:100%; height:auto;" />

  <p style="font-size:16px; margin:0;">
    <em>Empowering young minds to think creatively, code intelligently, and build the future with AI.</em>
  </p>
</div>
"""

display(HTML(html))

## **What is NumPy?**

NumPy is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

**Table of Contents:**
1. [Importing NumPy](#1)
2. [Creating and Manipulating NumPy Arrays](#2)
3. [NumPy Arrays vs Python Lists](#3)
4. [Indexing and Slicing NumPy Arrays](#4)
5. [Vectorized Mathematical Operations](#5)
6. [Other Common NumPy Methods](#6)
7. [Exercises](#7)

---
<a name='1'></a>
### 1. **Importing NumPy**

In [2]:
import numpy as np

---
<a name='2'></a>
### 2. **Creating and Manipulating NumPy Arrays**

You can create NumPy arrays from Python lists or use built-in NumPy functions.

In [ ]:
# Creating a one-dimensional array from a list
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
numpy_array_from_list

array([1, 2, 3, 4, 5])

In [ ]:
# Creating a one-dimensional array of zeros
numpy_array_zeros = np.zeros((5))
numpy_array_zeros

array([0., 0., 0., 0., 0.])

In [62]:
# Creating a one-dimensional array of ones

# The `np.ones()` function in NumPy is used to create an array where every element is the number one. 
# This can be particularly useful when you need a starting point for calculations or when you need an array of a certain size with a default value of one.

# You can specify the shape of the array you want to create, and optionally, you can also specify the data type of the elements.
# Where:
# - `shape`: the shape of the new array, e.g., `(2, 3)` for a 2x3 matrix.
# - `dtype`: the desired data type for the elements. Default is Float (optional).

numpy_array_ones = np.ones((5))
numpy_array_ones

array([1., 1., 1., 1., 1.])

In [ ]:
# Creating a one-dimensional array with a range of values
numpy_array_range = np.arange(10)
numpy_array_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating a one-dimensional array with linearly spaced values

# The `np.linspace()` function in NumPy is used to generate an array of evenly spaced values. 
# It's particularly useful when you need to create an array with a specific number of points, spaced uniformly over a specified interval.

# The function takes three main arguments: the `start` value, the `stop` value, and the `number of points`` to generate. It returns an array of evenly spaced values over this range.
# Where:
# - `start`: the starting value of the sequence.
# - `stop`: the end value of the sequence.
# - `num`: the number of samples to generate. Default is 50.

numpy_array_linspace = np.linspace(0, 10, 5)
numpy_array_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

An array can have any number of dimensions. A one-dimensional (1D) array is like a list of items, a two-dimensional (2D) array is like a table with rows and columns, and so on.

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

Reshaping NumPy arrays allows you to change the dimensions of an existing array without altering its data. This is useful for preparing data for mathematical operations, machine learning models, or visualization tasks.

In [ ]:
# We can get the shape of the array using the .shape attribute
array_2d.shape

(2, 3)

In [ ]:
# Reshaping the two-dimensional array to 3 rows and 2 columns
reshaped_array = array_2d.reshape(3, 2)
reshaped_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
reshaped_array.shape

(3, 2)

---
<a name='3'></a>
### 3. **NumPy Arrays vs. Python Lists**

NumPy arrays are more efficient than Python lists for numerical operations because they are designed for vectorized operations, which perform calculations on entire arrays at once without explicit loops.

In [15]:
import time

In [16]:
# Create a large Python list and a NumPy array
list_data = list(range(1000000))
numpy_array = np.arange(1000000)

In [17]:
# Measure time for element-wise addition using Python list
start_time = time.time()
result_list = [x + 1 for x in list_data]
end_time = time.time()
print(f"Time taken for Python list: {end_time - start_time:.6f} seconds")

Time taken for Python list: 0.035044 seconds


In [18]:
# Measure time for element-wise addition using NumPy array
start_time = time.time()
result_array = numpy_array + 1
end_time = time.time()
print(f"Time taken for NumPy array: {end_time - start_time:.6f} seconds")

Time taken for NumPy array: 0.000894 seconds


---
<a name='4'></a>
### 4. **Indexing and Slicing NumPy Arrays**

NumPy arrays can be indexed and sliced similar to Python lists, but with more powerful options for multi-dimensional arrays.

In [19]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Accessing elements
print("\nElement at (0, 1):", data[0, 1])


Element at (0, 1): 2


In [21]:
# Slicing rows and columns
print("\nFirst row:", data[0, :])
print("\nSecond column:", data[:, 1])
print("\nSub-array:\n", data[0:2, 1:3])


First row: [1 2 3]

Second column: [2 5 8]

Sub-array:
 [[2 3]
 [5 6]]


---
<a name='6'></a>
### 5. **Vectorized Mathematical Operations**

NumPy allows you to perform element-wise mathematical operations directly on arrays.

In [25]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [26]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [29]:
# Element-wise addition
addition_result = a + b
addition_result

array([5, 7, 9])

In [ ]:
# Element-wise multiplication
multiplication_result = a * b
multiplication_result

array([ 4, 10, 18])

**Broadcasting** in NumPy is a powerful mechanism that allows arrays of different shapes to be used together in arithmetic operations. It works by automatically expanding the smaller array along the mismatched dimensions so that both arrays have compatible shapes for element-wise operations.

In [33]:
# Broadcasting
c = np.array([10])
broadcast_result = a + c
broadcast_result

array([11, 12, 13])

---
<a name='6'></a>
### 6. **Other Common NumPy Methods**

NumPy provides a wide range of methods for creating, manipulating, and performing mathematical operations on arrays.

#### 6.1 **np.dot()**

The `np.dot()` function is used to compute the dot product of two arrays. In linear algebra, the dot product is an algebraic operation that takes two equal-length sequences of numbers and returns a single number. This function is particularly important in various mathematical computations including matrix multiplication.

For one-dimensional arrays, it computes the inner product of the vectors. For two-dimensional arrays, it computes the matrix multiplication.

The syntax is:

$$
\text{np.dot(a, b)}
$$

Where:
- `a` and `b` are input arrays.

It's important to ensure that the dimensions of the arrays are aligned properly for the operation (e.g., the number of columns in `a` should match the number of rows in `b` for matrix multiplication).


In [41]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
print("Array A:", array_a)
print("Array B:", array_b)

Array A: [1 2 3]
Array B: [4 5 6]


In [ ]:
# Dot product of two 1-d arrays
dot_product = np.dot(a, b)
dot_product

np.int64(32)

In [39]:
array_c = np.array([[1, 2], [3, 4]])
array_d = np.array([[5, 6], [7, 8]])
print("Array C:\n", array_c)
print("\nArray D:\n", array_d)

Array C:
 [[1 2]
 [3 4]]

Array D:
 [[5 6]
 [7 8]]


In [40]:
# Dot product of two 2-d arrays
dot_product = np.dot(array_c, array_d)
print("\nDot product of two 2-d arrays:\n", dot_product)


Dot product of two 2-d arrays:
 [[19 22]
 [43 50]]


#### 6.2 **np.transpose()**

The `np.transpose()` function is used to transpose a given array. In simple terms, transposing means changing the rows of an array into columns and vice versa. This is particularly useful in linear algebra and in various data manipulation tasks.

For a 2D array, transposing will swap the rows and columns. For a 1D array, the transpose will return the same array as there's only one dimension.

The syntax is:

$$
\text{np.transpose(a)}
$$

Where:
- `a`: the array to be transposed.

Transposing is a fundamental operation in many matrix manipulations and is widely used in mathematical computations.


In [ ]:
array_1d = np.array([1, 2, 3, 4, 5])
print("Array 1D:", array_1d)
print("Array 1D Shape:", array_1d.shape)

Array 1D: [1 2 3 4 5]
Array A Shape: (5,)


In [54]:
# Transposing the 1-D Array
transposed_array_1d = np.transpose(array_1d)
print("Array 1D:", transposed_array_1d)
print("Transposed Array 1D Shape:", transposed_array_1d.shape)

Array 1D: [1 2 3 4 5]
Transposed Array 1D Shape: (5,)


In [56]:
# Creating Arrays
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:\n", array_2d)
print("Array 2D Shape:", array_2d.shape)

Array 2D:
 [[1 2 3]
 [4 5 6]]
Array 2D Shape: (2, 3)


In [57]:
# Transposing the 2-D Array
transposed_array_2d = np.transpose(array_2d)
print("\nTransposed Array 2D:\n", transposed_array_2d)
print("Transposed Array 2D Shape:", transposed_array_2d.shape)


Transposed Array 2D:
 [[1 4]
 [2 5]
 [3 6]]
Transposed Array 2D Shape: (3, 2)


#### 6.3 **np.vstack()**

The `np.vstack()` function in NumPy is used to stack arrays vertically. This means that you can take multiple arrays and combine them into one array by stacking them on top of each other. This function is particularly useful when you need to combine data from different sources or when preparing data for certain types of analysis.

The arrays that you want to stack must have the same shape along all but the first axis. This requirement ensures that they can be stacked neatly on top of each other.

The syntax is:

$$
\text{np.vstack[arr1, arr2, ... , n]}
$$

Using `np.vstack()`, you can easily merge data from different arrays into a single array for further analysis.


In [ ]:
# Creating two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [1 2 3]
Array 2: [4 5 6]


In [ ]:
# Stacking arrays vertically
stacked_array = np.vstack([array1, array2])

print("Vertically stacked array:\n", stacked_array)

Vertically stacked array:
 [[1 2 3]
 [4 5 6]]


#### 6.4 **np.clip()**

The `np.clip()` function in NumPy is used to clip (limit) the values in an array. It allows you to set a minimum and maximum value, and any values in the array that are outside of this interval will be clipped to the interval edges. This function is particularly useful for data normalization, outlier removal, or enforcing bounds in numerical calculations.

The syntax is:

$$
\text{np.clip(a, min, max)}
$$

Where:
- `a`: the input array.
- `min`: the minimum value to clip to.
- `max`: the maximum value to clip to.

Using `np.clip()`, you can easily ensure that your data stays within specified bounds.


In [ ]:
# Creating an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Clipping the array
clipped_array = np.clip(array, 3, 7)

print("Original array:\n", array)
print("\nClipped array:\n", clipped_array)

#### 6.5 **np.zeros_like()**

The `np.zeros_like()` function in NumPy is used to create a new array with the same shape and type as an existing array, but filled with zeros. This is particularly useful when you need an array of zeros that matches the dimensions of another array, often used for initialization in various algorithms and computations.

The syntax is:

$$
\text{np.zeros\_like(a, dtype=None)}
$$

Where:
- `a`: the shape and data-type of `a` define these same attributes of the returned array.
- `dtype`: is the desired data-type for the array (optional).

This function is a quick and efficient way to initialize arrays for computations, particularly when working with arrays of the same size.


In [3]:
# Creating an existing array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])

print("Existing array:\n", existing_array)

Existing array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Creating a zeros-like array
zeros_like_array = np.zeros_like(existing_array)

print("\nZeros-like array:\n", zeros_like_array)


Zeros-like array:
 [[0 0 0]
 [0 0 0]]


#### 6.6 **np.flipud()**

The `np.flipud()` function in NumPy, which stands for `flip up down`, is used to flip an array vertically (upside down). This means that the elements of the array are rearranged as if you had mirrored them along the horizontal axis.

For a 1D array, `np.flipud()` will simply reverse the order of the elements. For a 2D array, it flips the elements along the first axis.

The syntax is:

$$
\text{np.flipud(m)}
$$

Where:
- `m`: the input array.

`np.flipud()` is a simple yet powerful tool for array manipulation, particularly in graphical and spatial data analysis.


In [6]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D Array:\n", array_1d)
print("\n2D Array:\n", array_2d)

1D Array:
 [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Flipping the 1D array
flipped_1d = np.flipud(array_1d)

print("Flipped 1D array:\n", flipped_1d)

Flipped 1D array:
 [5 4 3 2 1]


In [9]:
# Flipping the 2D array upside down
flipped_2d = np.flipud(array_2d)

print("\nFlipped 2D array:\n", flipped_2d)


Flipped 2D array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 6.7 **np.fliplr()**

The `np.fliplr()` function in NumPy, which stands for `flip left right`, is used to flip arrays horizontally (left to right). This operation mirrors the elements in each row for a 2D array. It's particularly useful in image processing and other applications where such a transformation is needed.

Note that `np.fliplr()` can only be used on arrays that are at least 2D. For a 1D array, this function will not perform any flip operation.

The syntax is:

$$
\text{np.fliplr(m)}
$$

Where:
- `m`: the input array, which must be at least 2D.

Flipping arrays horizontally is a common operation in data manipulation, especially when dealing with spatial data or when specific orientations of data are required.


In [10]:
# Flipping the array left to right
flipped_array = np.fliplr(array_2d)

print("\nFlipped left to right 2D array:\n", flipped_array)


Flipped left to right 2D array:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


#### 6.8 **np.mean() / np.median / ...**

NumPy provides several functions to calculate various types of averages (measures of central tendency) for arrays. These functions are optimized for performance on numerical data and are widely used in statistics and data analysis.

- **`np.mean()`**: Computes the arithmetic mean (average) of the array elements.
$$
\text{np.mean(a, axis=None)}
$$
Where:
- `a`: the input array.
- `axis`: the axis along which the means are computed (optional).

- **`np.median()`**: Computes the median of the array elements. The median is the middle value in a sorted list of numbers.
$$
\text{np.median(a, axis=None)}
$$
Where:
- `a`: the input array.
- `axis`: the axis along which the medians are computed (optional).

- **`np.average()`**: Computes the weighted average of the array elements along a specified axis.
$$
\text{np.average(a, axis=None, weights=None)}
$$
Where:
- `a`: the input array.
- `axis`: the axis along which the average is computed (optional).
- `weights`: An array of weights associated with the values in `a` (optional).

These functions are essential for summarizing and understanding the distribution of data in NumPy arrays.

In [13]:
# Creating an array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [14]:
# Calculating the mean
mean_value = np.mean(data)
print("Mean:", mean_value)

Mean: 5.5


In [15]:
# Calculating the median
median_value = np.median(data)
print("Median:", median_value)

Median: 5.5


In [16]:
# Calculating the weighted average
weights = np.array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2]) # Example weights
weighted_average = np.average(data, weights=weights)
print("Weighted Average:", weighted_average)

Weighted Average: 6.333333333333333


In [17]:
# Calculating mean along an axis for a 2D array
data_2d = np.array([[1, 2, 3], [4, 5, 6]])
mean_axis_0 = np.mean(data_2d, axis=0) # Mean of each column
mean_axis_1 = np.mean(data_2d, axis=1) # Mean of each row

print("\nOriginal 2D array:\n", data_2d)
print("\nMean along axis 0 (columns):", mean_axis_0)
print("Mean along axis 1 (rows):", mean_axis_1)


Original 2D array:
 [[1 2 3]
 [4 5 6]]

Mean along axis 0 (columns): [2.5 3.5 4.5]
Mean along axis 1 (rows): [2. 5.]


---
<a name='7'></a>
### 7. **Practice Exercises**

Test your understanding of NumPy with these exercises!

#### Exercise 1: Creating Arrays
Create a 1D NumPy array containing the numbers from 15 to 25 (inclusive) using `np.arange()`.

In [ ]:
# Your code here

#### Exercise 2: Array with Specific Values
Create a 1D array of 8 evenly spaced values between 0 and 1 (inclusive) using `np.linspace()`.

In [ ]:
# Your code here

#### Exercise 3: Creating 2D Arrays
Create a 2D array (matrix) with 4 rows and 3 columns filled with zeros.

In [ ]:
# Your code here

#### Exercise 4: Reshaping Arrays
Create a 1D array with values from 1 to 12 using `np.arange()`, then reshape it into a 3x4 matrix.

In [ ]:
# Your code here

#### Exercise 5: Array Indexing
Given the array `arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`, extract the element at row 1, column 2.

In [ ]:
# Your code here
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

#### Exercise 6: Array Slicing
Using the same array from Exercise 5, extract the last two rows and all columns.

In [ ]:
# Your code here
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

#### Exercise 7: Element-wise Operations
Create two arrays: `x = np.array([1, 2, 3, 4, 5])` and `y = np.array([10, 20, 30, 40, 50])`. Compute their element-wise sum, difference, and product.

In [ ]:
# Your code here

#### Exercise 8: Broadcasting
Create an array `z = np.array([5, 10, 15, 20])` and add the scalar value 100 to each element using broadcasting.

In [ ]:
# Your code here

#### Exercise 9: Dot Product
Compute the dot product of two 1D arrays: `a = np.array([2, 3, 4])` and `b = np.array([1, 5, 7])`.

In [ ]:
# Your code here

#### Exercise 10: Transposing Arrays
Create a 2D array `matrix = np.array([[1, 2, 3], [4, 5, 6]])` and transpose it using `np.transpose()`.

In [ ]:
# Your code here

#### Exercise 11: Vertical Stacking
Create two arrays `arr1 = np.array([1, 2, 3])` and `arr2 = np.array([4, 5, 6])`, then stack them vertically using `np.vstack()`.

In [ ]:
# Your code here

#### Exercise 12: Clipping Values
Create an array `data = np.array([5, 12, 18, 3, 25, 8, 30])` and clip all values to be between 10 and 20 using `np.clip()`.

In [ ]:
# Your code here

#### Exercise 13: Flipping Arrays
Create a 2D array `grid = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`. Flip it vertically using `np.flipud()` and then flip it horizontally using `np.fliplr()`.

In [ ]:
# Your code here

#### Exercise 14: Statistical Operations
Create an array `scores = np.array([85, 90, 78, 92, 88, 76, 95, 89])`. Calculate the mean, median, and maximum value of the scores.

In [ ]:
# Your code here

#### Exercise 15: Challenge - Combining Concepts
Create a 4x4 matrix of random integers between 1 and 50 using `np.random.randint(1, 51, (4, 4))`. Then:
1. Extract the second and third rows
2. Calculate the mean of each column
3. Replace all values greater than 30 with 30 using `np.clip()`

In [ ]:
# Your code here