In [8]:
# @title
from IPython.display import display, HTML

display(HTML("""
<script>
const firstCell = document.querySelector('.cell.code_cell');
if (firstCell) {
  firstCell.querySelector('.input').style.pointerEvents = 'none';
  firstCell.querySelector('.input').style.opacity = '0.5';
}
</script>
"""))

html = """
<div style="display:flex; flex-direction:column; align-items:center; text-align:center; gap:12px; padding:8px;">
  <h1 style="margin:0;">👋 Welcome to <span style="color:#1E88E5;">Algopath Coding Academy</span>!</h1>

  <img src="https://raw.githubusercontent.com/sshariqali/mnist_pretrained_model/main/algopath_logo.jpg"
       alt="Algopath Coding Academy Logo"
       width="400"
       style="border-radius:15px; box-shadow:0 4px 12px rgba(0,0,0,0.2); max-width:100%; height:auto;" />

  <p style="font-size:16px; margin:0;">
    <em>Empowering young minds to think creatively, code intelligently, and build the future with AI.</em>
  </p>
</div>
"""

display(HTML(html))

## **What is NumPy?**

NumPy is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

**Table of Contents:**
1. [Importing NumPy](#1)
2. [Creating and Manipulating NumPy Arrays](#2)
3. [NumPy Arrays vs Python Lists](#3)
4. [Indexing and Slicing NumPy Arrays](#4)
5. [Vectorized Mathematical Operations](#5)
6. [Other Common NumPy Methods](#6)
7. [Reading Materials](#7)

---
<a name='1'></a>
### 1. **Importing NumPy**

In [3]:
import numpy as np

---
<a name='2'></a>
### 2. **Creating and Manipulating NumPy Arrays**

You can create NumPy arrays from Python lists or use built-in NumPy functions.

In [4]:
# Creating a one-dimensional array from a list
numpy_array_from_list = np.array([24, 57, 12, 89, 43])
numpy_array_from_list

array([24, 57, 12, 89, 43])

In [5]:
# Creating a one-dimensional array of zeros
numpy_array_zeros = np.zeros((5))
numpy_array_zeros

array([0., 0., 0., 0., 0.])

In [6]:
# Creating a one-dimensional array of ones

# The `np.ones()` function in NumPy is used to create an array where every element is the number one. 
# This can be particularly useful when you need a starting point for calculations or when you need an array of a certain size with a default value of one.

# You can specify the shape of the array you want to create, and optionally, you can also specify the data type of the elements.
# Where:
# - `shape`: the shape of the new array, e.g., `(2, 3)` for a 2x3 matrix.
# - `dtype`: the desired data type for the elements. Default is Float (optional).

numpy_array_ones = np.ones((5))
numpy_array_ones

array([1., 1., 1., 1., 1.])

In [7]:
# Creating a one-dimensional array with a range of values

numpy_array_range = np.arange(0,10)
numpy_array_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

An array can have any number of dimensions. A one-dimensional (1D) array is like a list of items, a two-dimensional (2D) array is like a table with rows and columns, and so on.

In [8]:
array_2d = np.array([[12, 34, 56], [78, 90, 23]])
array_2d

array([[12, 34, 56],
       [78, 90, 23]])

Reshaping NumPy arrays allows you to change the dimensions of an existing array without altering its data. This is useful for preparing data for mathematical operations, machine learning models, or visualization tasks.

In [9]:
# We can get the shape of the array using the .shape attribute
array_2d.shape

(2, 3)

In [10]:
# Reshaping the two-dimensional array to 3 rows and 2 columns
reshaped_array = array_2d.reshape(3, 2)
reshaped_array

array([[12, 34],
       [56, 78],
       [90, 23]])

In [11]:
reshaped_array.shape

(3, 2)

---
<a name='3'></a>
### 3. **NumPy Arrays vs. Python Lists**

NumPy arrays are more efficient than Python lists for numerical operations because they are designed for vectorized operations, which perform calculations on entire arrays at once without explicit loops.

In [12]:
import time

In [13]:
# Create a large Python list and a NumPy array
list_data = list(range(1000000))
numpy_array = np.arange(1000000)

In [14]:
# Measure time for element-wise addition using Python list
start_time = time.time()
result_list = [x + 1 for x in list_data]
end_time = time.time()
print(f"Time taken for Python list: {end_time - start_time:.6f} seconds")

Time taken for Python list: 0.061595 seconds


In [15]:
# Measure time for element-wise addition using NumPy array
start_time = time.time()
result_array = numpy_array + 1
end_time = time.time()
print(f"Time taken for NumPy array: {end_time - start_time:.6f} seconds")

Time taken for NumPy array: 0.008649 seconds


---
<a name='4'></a>
### 4. **Indexing and Slicing NumPy Arrays**

NumPy arrays can be indexed and sliced similar to Python lists, but with more powerful options for multi-dimensional arrays.

In [16]:
data = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
data

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [17]:
# Accessing elements
print("\nElement at (0, 1):", data[0, 1])


Element at (0, 1): 22


In [18]:
# Slicing rows and columns
print("\nFirst row:", data[0, :])
print("\nSecond column:", data[:, 1])
print("\nSub-array:\n", data[0:2, 1:3])


First row: [11 22 33]

Second column: [22 55 88]

Sub-array:
 [[22 33]
 [55 66]]


---
<a name='6'></a>
### 5. **Vectorized Mathematical Operations**

NumPy allows you to perform element-wise mathematical operations directly on arrays.

In [19]:
a = np.array([21, 8, 64])
a

array([21,  8, 64])

In [20]:
b = np.array([19, 81, 26])
b

array([19, 81, 26])

In [21]:
# Element-wise addition
addition_result = a + b
addition_result

array([40, 89, 90])

In [22]:
# Element-wise multiplication
multiplication_result = a * b
multiplication_result

array([ 399,  648, 1664])

**Broadcasting** in NumPy is a powerful mechanism that allows arrays of different shapes to be used together in arithmetic operations. It works by automatically expanding the smaller array along the mismatched dimensions so that both arrays have compatible shapes for element-wise operations.

In [23]:
# Broadcasting
c = np.array([10])
broadcast_result = a + c
broadcast_result

array([31, 18, 74])

---
<a name='6'></a>
### 6. **Other Common NumPy Methods**

NumPy provides a wide range of methods for creating, manipulating, and performing mathematical operations on arrays.

#### 6.1 **np.dot()**

The `np.dot()` function is used to compute the dot product of two arrays. In linear algebra, the dot product is an algebraic operation that takes two equal-length sequences of numbers and returns a single number. This function is particularly important in various mathematical computations including matrix multiplication.

For one-dimensional arrays, it computes the inner product of the vectors. For two-dimensional arrays, it computes the matrix multiplication.

The syntax is:

$$
\text{np.dot(a, b)}
$$

Where:
- `a` and `b` are input arrays.

It's important to ensure that the dimensions of the arrays are aligned properly for the operation (e.g., the number of columns in `a` should match the number of rows in `b` for matrix multiplication).

In [24]:
array_a = np.array([12, 34, 56])
array_b = np.array([78, 90, 23])
print("Array A:", array_a)
print("Array B:", array_b)

Array A: [12 34 56]
Array B: [78 90 23]


In [25]:
# Dot product of two 1-d arrays
dot_product = np.dot(a, b)
dot_product

np.int64(2711)

In [26]:
array_c = np.array([[16, 81], [3, 28]])
array_d = np.array([[55, 49], [71, 98]])
print("Array C:\n", array_c)
print("\nArray D:\n", array_d)

Array C:
 [[16 81]
 [ 3 28]]

Array D:
 [[55 49]
 [71 98]]


In [27]:
# Dot product of two 2-d arrays
dot_product = np.dot(array_c, array_d)
print("\nDot product of two 2-d arrays:\n", dot_product)


Dot product of two 2-d arrays:
 [[6631 8722]
 [2153 2891]]


#### 6.2 **np.transpose()**

The `np.transpose()` function is used to transpose a given array. In simple terms, transposing means changing the rows of an array into columns and vice versa. This is particularly useful in linear algebra and in various data manipulation tasks.

For a 2D array, transposing will swap the rows and columns. For a 1D array, the transpose will return the same array as there's only one dimension.

The syntax is:

$$
\text{np.transpose(a)}
$$

Where:
- `a`: the array to be transposed.

Transposing is a fundamental operation in many matrix manipulations and is widely used in mathematical computations.

In [28]:
array_1d = np.array([56, 12, 90, 34, 78])
print("Array 1D:", array_1d)
print("Array 1D Shape:", array_1d.shape)

Array 1D: [56 12 90 34 78]
Array 1D Shape: (5,)


In [29]:
# Transposing the 1-D Array
transposed_array_1d = np.transpose(array_1d)
print("Array 1D:", transposed_array_1d)
print("Transposed Array 1D Shape:", transposed_array_1d.shape)

Array 1D: [56 12 90 34 78]
Transposed Array 1D Shape: (5,)


In [30]:
# Creating Arrays
array_2d = np.array([[24, 89, 43], [12, 57, 76]])
print("Array 2D:\n", array_2d)
print("Array 2D Shape:", array_2d.shape)

Array 2D:
 [[24 89 43]
 [12 57 76]]
Array 2D Shape: (2, 3)


In [31]:
# Transposing the 2-D Array
transposed_array_2d = np.transpose(array_2d)
print("\nTransposed Array 2D:\n", transposed_array_2d)
print("Transposed Array 2D Shape:", transposed_array_2d.shape)


Transposed Array 2D:
 [[24 12]
 [89 57]
 [43 76]]
Transposed Array 2D Shape: (3, 2)


#### 6.3 **np.vstack()**


The `np.vstack()` function in NumPy is used to stack arrays vertically. This means that you can take multiple arrays and combine them into one array by stacking them on top of each other. This function is particularly useful when you need to combine data from different sources or when preparing data for certain types of analysis.

The arrays that you want to stack must have the same shape along all but the first axis. This requirement ensures that they can be stacked neatly on top of each other.

The syntax is:

$$
\text{np.vstack[arr1, arr2, ... , n]}
$$

Using `np.vstack()`, you can easily merge data from different arrays into a single array for further analysis.

In [32]:
# Creating two arrays
array1 = np.array([12, 34, 56])
array2 = np.array([78, 90, 23])

print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [12 34 56]
Array 2: [78 90 23]


In [33]:
# Stacking arrays vertically
stacked_array = np.vstack([array1, array2])

print("Vertically stacked array:\n", stacked_array)

Vertically stacked array:
 [[12 34 56]
 [78 90 23]]


#### 6.4 **np.clip()**

The `np.clip()` function in NumPy is used to clip (limit) the values in an array. It allows you to set a minimum and maximum value, and any values in the array that are outside of this interval will be clipped to the interval edges. This function is particularly useful for data normalization, outlier removal, or enforcing bounds in numerical calculations.

The syntax is:

$$
\text{np.clip(a, min, max)}
$$

Where:
- `a`: the input array.
- `min`: the minimum value to clip to.
- `max`: the maximum value to clip to.

Using `np.clip()`, you can easily ensure that your data stays within specified bounds.

In [ ]:
# Creating an array
array = np.array([37, 84, 21, 56, 99, 42, 73, 18, 65])

# Clipping the array
clipped_array = np.clip(array, 3, 7)

print("Original array:\n", array)
print("\nClipped array:\n", clipped_array)

#### 6.5 **np.zeros_like()**

The `np.zeros_like()` function in NumPy is used to create a new array with the same shape and type as an existing array, but filled with zeros. This is particularly useful when you need an array of zeros that matches the dimensions of another array, often used for initialization in various algorithms and computations.

The syntax is:

$$
\text{np.zeros\_like(a, dtype=None)}
$$

Where:
- `a`: the shape and data-type of `a` define these same attributes of the returned array.
- `dtype`: is the desired data-type for the array (optional).

This function is a quick and efficient way to initialize arrays for computations, particularly when working with arrays of the same size.

In [3]:
# Creating an existing array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])

print("Existing array:\n", existing_array)

Existing array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Creating a zeros-like array
zeros_like_array = np.zeros_like(existing_array)

print("\nZeros-like array:\n", zeros_like_array)


Zeros-like array:
 [[0 0 0]
 [0 0 0]]


#### 6.6 **np.flipud()**


The `np.flipud()` function in NumPy, which stands for `flip up down`, is used to flip an array vertically (upside down). This means that the elements of the array are rearranged as if you had mirrored them along the horizontal axis.

For a 1D array, `np.flipud()` will simply reverse the order of the elements. For a 2D array, it flips the elements along the first axis.

The syntax is:

$$
\text{np.flipud(m)}
$$

Where:
- `m`: the input array.

`np.flipud()` is a simple yet powerful tool for array manipulation, particularly in graphical and spatial data analysis.

In [6]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D Array:\n", array_1d)
print("\n2D Array:\n", array_2d)

1D Array:
 [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Flipping the 1D array
flipped_1d = np.flipud(array_1d)

print("Flipped 1D array:\n", flipped_1d)

Flipped 1D array:
 [5 4 3 2 1]


In [9]:
# Flipping the 2D array upside down
flipped_2d = np.flipud(array_2d)

print("\nFlipped 2D array:\n", flipped_2d)


Flipped 2D array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 6.7 **np.fliplr()**


The `np.fliplr()` function in NumPy, which stands for `flip left right`, is used to flip arrays horizontally (left to right). This operation mirrors the elements in each row for a 2D array. It's particularly useful in image processing and other applications where such a transformation is needed.

Note that `np.fliplr()` can only be used on arrays that are at least 2D. For a 1D array, this function will not perform any flip operation.

The syntax is:

$$
\text{np.fliplr(m)}
$$

Where:
- `m`: the input array, which must be at least 2D.

Flipping arrays horizontally is a common operation in data manipulation, especially when dealing with spatial data or when specific orientations of data are required.

In [10]:
# Flipping the array left to right
flipped_array = np.fliplr(array_2d)

print("\nFlipped left to right 2D array:\n", flipped_array)


Flipped left to right 2D array:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


#### 6.8 **np.mean() / np.median / ...**

NumPy provides several functions to calculate various types of averages (measures of central tendency) for arrays. These functions are optimized for performance on numerical data and are widely used in statistics and data analysis.

- **`np.mean()`**: Computes the arithmetic mean (average) of the array elements.
$$
\text{np.mean(a, axis=None)}
$$
Where:
- `a`: the input array.
- `axis`: the axis along which the means are computed (optional).

- **`np.median()`**: Computes the median of the array elements. The median is the middle value in a sorted list of numbers.
$$
\text{np.median(a, axis=None)}
$$
Where:
- `a`: the input array.
- `axis`: the axis along which the medians are computed (optional).

- **`np.average()`**: Computes the weighted average of the array elements along a specified axis.
$$
\text{np.average(a, axis=None, weights=None)}
$$
Where:
- `a`: the input array.
- `axis`: the axis along which the average is computed (optional).
- `weights`: An array of weights associated with the values in `a` (optional).

These functions are essential for summarizing and understanding the distribution of data in NumPy arrays.

In [34]:
# Creating an array
data = np.array([37, 84, 21, 56, 99, 42, 73, 18, 65, 58])

In [36]:
# Calculating the mean
mean_value = np.mean(data)
print("Mean:", mean_value)

Mean: 55.3


In [37]:
# Calculating the median
median_value = np.median(data)
print("Median:", median_value)

Median: 57.0


In [38]:
# Calculating the weighted average
weights = np.array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2]) # Example weights
weighted_average = np.average(data, weights=weights)
print("Weighted Average:", weighted_average)

Weighted Average: 53.93333333333333


In [39]:
# Calculating mean along an axis for a 2D array
data_2d = np.array([[47, 82, 19], [63, 28, 54]])
mean_axis_0 = np.mean(data_2d, axis=0) # Mean of each column
mean_axis_1 = np.mean(data_2d, axis=1) # Mean of each row

print("\nOriginal 2D array:\n", data_2d)
print("\nMean along axis 0 (columns):", mean_axis_0)
print("Mean along axis 1 (rows):", mean_axis_1)


Original 2D array:
 [[47 82 19]
 [63 28 54]]

Mean along axis 0 (columns): [55.  55.  36.5]
Mean along axis 1 (rows): [49.33333333 48.33333333]


---
<a name='7'></a>
### 7. **Reading Materials**

This section contains other important concepts that are incredibly useful for real-world projects.

#### 7.1 **Boolean Indexing (Masking)**

In NumPy, you can use logical conditions to filter data. This is often faster than using if statements or loops.

In [40]:
# Create an array of random integers
data = np.array([10, 25, 30, 45, 50, 65])

In [41]:
# Create a boolean mask for values greater than 40
mask = data > 40
print("Mask:", mask)

Mask: [False False False  True  True  True]


In [42]:
# Use the mask to filter the data
filtered_data = data[mask]
print("Filtered Data:", filtered_data)

Filtered Data: [45 50 65]


#### 7.2 **Copies vs. Views**

One of the most common mistakes in NumPy is forgetting that slicing often creates a view, not a copy. If you change a view, you change the original array!

**View**: A "window" into the original data. Changes here affect the source.

**Copy**: A brand new array in memory. Changes here are isolated.

In [43]:
# Start with an original array
original = np.array([10, 2, 90, 22, 63])
original_2 = np.array([10, 2, 90, 22, 63])

In [44]:
# Create a slice (view)
my_view = original[0:2]
my_view[0] = 99  # Modifying the view

print("Original after modifying view:", original)  # [99, 2, 90, 22, 63]

Original after modifying view: [99  2 90 22 63]


In [45]:
# Create a copy
my_copy = original_2[0:2].copy()
my_copy[0] = 99  # Modifying the copy
    
print("Original after modifying copy:", original_2)  # [10, 2, 90, 22, 63]

Original after modifying copy: [10  2 90 22 63]


#### 7.3 **Saving and Loading Data**

When working on AI models, you often need to save your processed arrays to a file so you can use them later without re-running your code.

- `np.save('filename.npy', array)`: Saves a single array in a compressed format.

- `np.load('filename.npy')`: Loads the array back into your script.

- `np.savetxt('file.csv', array)`: Saves data as a readable text/CSV file.

In [ ]:
# Create an array to save
my_array = np.array([10, 20, 30, 40, 50])

In [ ]:
# Save to a binary file (.npy)
np.save('my_array_file.npy', my_array)
print("Saved my_array_file.npy")

In [ ]:
# Load it back
loaded_array = np.load('my_array_file.npy')
print("Loaded array:", loaded_array)

#### 7.4 **Common Utility Functions**

NumPy provides many utility functions that make common tasks easier.

- `np.eye(n)`: Creates an 2D array with ones on the diagonal and zeros elsewhere (Identity matrix).
- `np.unique(array)`: Returns the sorted unique elements of an array.
- `np.flatten()`: Collapses a multi-dimensional array into a one-dimensional array.
- `np.argmax(array)`: Returns the index of the maximum value in the array.

In [ ]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

In [ ]:
# Find unique elements
repeated_data = np.array([1, 2, 2, 3, 3, 3, 4])
unique_elements = np.unique(repeated_data)
print("\nUnique Elements:", unique_elements)

In [ ]:
# Flatten a 2D array
matrix = np.array([[1, 2], [3, 4]])
flattened = matrix.flatten()
print("\nFlattened Array:", flattened)

In [ ]:
# Find the index of the max value
scores = np.array([10, 50, 90, 20])
max_index = np.argmax(scores)
print(f"\nMax value is {scores[max_index]} at index {max_index}")