In [8]:
# @title
from IPython.display import display, HTML

display(HTML("""
<script>
const firstCell = document.querySelector('.cell.code_cell');
if (firstCell) {
  firstCell.querySelector('.input').style.pointerEvents = 'none';
  firstCell.querySelector('.input').style.opacity = '0.5';
}
</script>
"""))

html = """
<div style="display:flex; flex-direction:column; align-items:center; text-align:center; gap:12px; padding:8px;">
  <h1 style="margin:0;">👋 Welcome to <span style="color:#1E88E5;">Algopath Coding Academy</span>!</h1>

  <img src="https://raw.githubusercontent.com/sshariqali/mnist_pretrained_model/main/algopath_logo.jpg"
       alt="Algopath Coding Academy Logo"
       width="400"
       style="border-radius:15px; box-shadow:0 4px 12px rgba(0,0,0,0.2); max-width:100%; height:auto;" />

  <p style="font-size:16px; margin:0;">
    <em>Empowering young minds to think creatively, code intelligently, and build the future with AI.</em>
  </p>
</div>
"""

display(HTML(html))

## **What is NumPy?**

NumPy is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

**Table of Contents:**
1. [Importing NumPy](#1)
2. [Creating anbd Manipulating NumPy Arrays](#2)
3. [NumPy Arrays vs Python Lists](#3)
4. [Indexing and Slicing NumPy Arrays](#4)
5. [Vectorized Mathematical Operations](#5)
6. [Commom NumPy Methods](#6)

---
<a name='1'></a>
### 1. **Importing NumPy**

In [ ]:
import numpy as np

---
<a name='2'></a>
### 2. **Creating and Manipulating NumPy Arrays**

You can create NumPy arrays from Python lists or use built-in NumPy functions.

In [ ]:
# Creating NumPy arrays
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
numpy_array_zeros = np.zeros((2, 3))
numpy_array_ones = np.ones((3, 2))
numpy_array_range = np.arange(10)
numpy_array_linspace = np.linspace(0, 10, 5)

print("From list:\n", numpy_array_from_list)
print("\nZeros:\n", numpy_array_zeros)
print("\nOnes:\n", numpy_array_ones)
print("\nRange:\n", numpy_array_range)
print("\nLinspace:\n", numpy_array_linspace)

# Reshaping arrays
reshaped_array = numpy_array_range.reshape(2, 5)
print("Reshaped array:", reshaped_array)

From list:
 [1 2 3 4 5]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Range:
 [0 1 2 3 4 5 6 7 8 9]

Linspace:
 [ 0.   2.5  5.   7.5 10. ]
Reshaped array: [[0 1 2 3 4]
 [5 6 7 8 9]]


An array can have any number of dimensions. A one-dimensional (1D) array is like a list of items, a two-dimensional (2D) array is like a table with rows and columns, and so on.

In [ ]:
# Creating a two-dimensional array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nTwo-dimensional array:\n", array_2d)

---
<a name='3'></a>
### 3. **NumPy Arrays vs. Python Lists**

NumPy arrays are more efficient than Python lists for numerical operations because they are designed for vectorized operations, which perform calculations on entire arrays at once without explicit loops.

In [ ]:
import time

# Create a large Python list and a NumPy array
list_data = list(range(1000000))
numpy_array = np.arange(1000000)

# Measure time for element-wise addition using Python list
start_time = time.time()
result_list = [x + 1 for x in list_data]
end_time = time.time()
print(f"Time taken for Python list: {end_time - start_time:.6f} seconds")

# Measure time for element-wise addition using NumPy array
start_time = time.time()
result_array = numpy_array + 1
end_time = time.time()
print(f"Time taken for NumPy array: {end_time - start_time:.6f} seconds")

Time taken for Python list: 0.047881 seconds
Time taken for NumPy array: 0.003701 seconds


---
<a name='4'></a>
### 4. **Indexing and Slicing NumPy Arrays**

NumPy arrays can be indexed and sliced similar to Python lists, but with more powerful options for multi-dimensional arrays.

In [ ]:
# Indexing and slicing
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", data)

# Accessing elements
print("\nElement at (0, 1):", data[0, 1])

# Slicing rows and columns
print("\nFirst row:", data[0, :])
print("\nSecond column:", data[:, 1])
print("\nSub-array:\n", data[0:2, 1:3])

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at (0, 1): 2

First row: [1 2 3]

Second column: [2 5 8]

Sub-array:
 [[2 3]
 [5 6]]


---
<a name='6'></a>
### 5. **Vectorized Mathematical Operations**

NumPy allows you to perform element-wise mathematical operations directly on arrays.

In [ ]:
# Vectorized operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
addition_result = a + b
print("Addition:", addition_result)

# Element-wise multiplication
multiplication_result = a * b
print("Multiplication:", multiplication_result)

# Broadcasting
c = np.array([10])
broadcast_result = a + c
print("Broadcasting:", broadcast_result)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Broadcasting: [11 12 13]


---
<a name='6'></a>
### 6. **Common NumPy Methods**

NumPy provides a wide range of methods for creating, manipulating, and performing mathematical operations on arrays.

#### 6.1 **np.dot()**

The `np.dot()` function is used to compute the dot product of two arrays. In linear algebra, the dot product is an algebraic operation that takes two equal-length sequences of numbers and returns a single number. This function is particularly important in various mathematical computations including matrix multiplication.

For one-dimensional arrays, it computes the inner product of the vectors. For two-dimensional arrays, it computes the matrix multiplication.

The syntax is:

$$
\text{np.dot(a, b)}
$$

Where:
- `a` and `b` are input arrays.

It's important to ensure that the dimensions of the arrays are aligned properly for the operation (e.g., the number of columns in `a` should match the number of rows in `b` for matrix multiplication).


In [ ]:
# Dot product of two 1-d arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
dot_product = np.dot(array_a, array_b)
print("Dot product of two 1-d arrays:\n", dot_product)

# Dot product of two 2-d arrays
array_c = np.array([[1, 2], [3, 4]])
array_d = np.array([[5, 6], [7, 8]])
dot_product = np.dot(array_c, array_d)
print("\nDot product of two 2-d arrays:\n", dot_product)

#### 6.2 **array.shape**

In NumPy, each array has an attribute called `shape`. This attribute is a tuple that indicates the size of each dimension of the array. Understanding the shape of an array is crucial, as many operations in NumPy depend on the array's dimensions.

For a 1D array, the shape would be `(n,)`, where `n` is the number of elements in the array. For a 2D array, the shape would be `(m, n)`, where `m` is the number of rows and `n` is the number of columns.

The syntax to get the shape of an array is:

$$
\text{array.shape}
$$

This attribute is used frequently in data manipulation and analysis to understand the structure of the data we are working with.


In [ ]:
# Creating arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Getting the shape of the arrays
shape_1d = array_1d.shape
shape_2d = array_2d.shape

print("Shape of the 1D array:", shape_1d)
print("Shape of the 2D array:", shape_2d)

#### 6.3 **np.transpose()**

The `np.transpose()` function is used to transpose a given array. In simple terms, transposing means changing the rows of an array into columns and vice versa. This is particularly useful in linear algebra and in various data manipulation tasks.

For a 2D array, transposing will swap the rows and columns. For a 1D array, the transpose will return the same array as there's only one dimension.

The syntax is:

$$
\text{np.transpose(a)}
$$

Where:
- `a`: the array to be transposed.

Transposing is a fundamental operation in many matrix manipulations and is widely used in mathematical computations.


In [ ]:
# Creating Arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing the 1-D Array
transposed_array_1d = np.transpose(array_1d)

# Transposing the 2-D Array
transposed_array_2d = np.transpose(array_2d)

print("Original 1-D array:\n", array_1d)
print("\nTransposed array:\n", transposed_array_1d)

print("\nOriginal 2-D array:\n", array_2d)
print("\nTransposed array:\n", transposed_array_2d)

#### 6.4 **np.linspace()**

The `np.linspace()` function in NumPy is used to generate an array of evenly spaced values. It's particularly useful when you need to create an array with a specific number of points, spaced uniformly over a specified interval.

The function takes three main arguments: the start value, the end value, and the number of points to generate. It returns an array of evenly spaced values over this range.

The syntax is:

$$
\text{np.linspace(start, stop, num=50, dtype=float)}
$$

Where:
- `start`: the starting value of the sequence.
- `stop`: the end value of the sequence.
- `num`: the number of samples to generate. Default is 50.
- `dtype`: The data type of the generated samples. Default is Float.

`np.linspace()` is very useful in data analysis and graphical plotting, where you need to represent continuous data intervals.


In [ ]:
# Generating an array with values from 0 to 10, with 5 elements
linear_space = np.linspace(1, 10, num=10, dtype='int')

print("Array with linearly spaced elements:\n", linear_space)

#### 6.5 **np.vstack()**

The `np.vstack()` function in NumPy is used to stack arrays vertically. This means that you can take multiple arrays and combine them into one array by stacking them on top of each other. This function is particularly useful when you need to combine data from different sources or when preparing data for certain types of analysis.

The arrays that you want to stack must have the same shape along all but the first axis. This requirement ensures that they can be stacked neatly on top of each other.

The syntax is:

$$
\text{np.vstack[array_1, array_2, ... , array_n]}
$$

Using `np.vstack()`, you can easily merge data from different arrays into a single array for further analysis.


In [ ]:
# Creating two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stacking arrays vertically
stacked_array = np.vstack([array1, array2])

print("Vertically stacked array:\n", stacked_array)

#### 6.6 **np.ones()**

The `np.ones()` function in NumPy is used to create an array where every element is the number one. This can be particularly useful when you need a starting point for calculations or when you need an array of a certain size with a default value of one.

You can specify the shape of the array you want to create, and optionally, you can also specify the data type of the elements.

The syntax is:

$$
\text{np.ones(shape, dtype=Float)}
$$

Where:
- `shape`: the shape of the new array, e.g., `(2, 3)` for a 2x3 matrix.
- `dtype`: the desired data type for the elements. Default is Float (optional).

The `np.ones()` function is a quick and easy way to create arrays for various purposes in numerical computations.


In [ ]:
# Creating a 3x3 array with all elements as 1
ones_array = np.ones((3, 3),dtype='int')

print("Array filled with ones:\n", ones_array)

#### 6.6 **np.clip()**

The `np.clip()` function in NumPy is used to clip (limit) the values in an array. It allows you to set a minimum and maximum value, and any values in the array that are outside of this interval will be clipped to the interval edges. This function is particularly useful for data normalization, outlier removal, or enforcing bounds in numerical calculations.

The syntax is:

$$
\text{np.clip(a, a_min, a_max)}
$$

Where:
- `a`: the input array.
- `a_min`: the minimum value to clip to.
- `a_max`: the maximum value to clip to.

Using `np.clip()`, you can easily ensure that your data stays within specified bounds.


In [ ]:
# Creating an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Clipping the array
clipped_array = np.clip(array, 3, 7)

print("Original array:\n", array)
print("\nClipped array:\n", clipped_array)

#### 6.7 **np.zeros_like()**

The `np.zeros_like()` function in NumPy is used to create a new array with the same shape and type as an existing array, but filled with zeros. This is particularly useful when you need an array of zeros that matches the dimensions of another array, often used for initialization in various algorithms and computations.

The syntax is:

$$
\text{np.zeros_like(a, dtype=None)}
$$

Where:
- `a`: the shape and data-type of `a` define these same attributes of the returned array.
- `dtype`: is the desired data-type for the array (optional).

This function is a quick and efficient way to initialize arrays for computations, particularly when working with arrays of the same size.


In [ ]:
# Creating an existing array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a zeros-like array
zeros_like_array = np.zeros_like(existing_array)

print("Existing array:\n", existing_array)
print("\nZeros-like array:\n", zeros_like_array)

#### 6.8 **np.flipud()**

The `np.flipud()` function in NumPy, which stands for `flip up down`, is used to flip an array vertically (upside down). This means that the elements of the array are rearranged as if you had mirrored them along the horizontal axis.

For a 1D array, `np.flipud()` will simply reverse the order of the elements. For a 2D array, it flips the elements along the first axis.

The syntax is:

$$
\text{np.flipud(m)}
$$

Where:
- `m`: the input array.

`np.flipud()` is a simple yet powerful tool for array manipulation, particularly in graphical and spatial data analysis.


In [ ]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flipping the 1D array
flipped_1d = np.flipud(array_1d)

# Flipping the 2D array upside down
flipped_2d = np.flipud(array_2d)

print("Original 1D array:\n", array_1d)
print("\nFlipped 1D array:\n", flipped_1d)
print("\nOriginal 2D array:\n", array_2d)
print("\nFlipped upside down 2D array:\n", flipped_2d)

#### 6.9 **np.fliplr()**

The `np.fliplr()` function in NumPy, which stands for `flip left right`, is used to flip arrays horizontally (left to right). This operation mirrors the elements in each row for a 2D array. It's particularly useful in image processing and other applications where such a transformation is needed.

Note that `np.fliplr()` can only be used on arrays that are at least 2D. For a 1D array, this function will not perform any flip operation.

The syntax is:

$$
\text{np.fliplr(m)}
$$

Where:
- `m`: the input array, which must be at least 2D.

Flipping arrays horizontally is a common operation in data manipulation, especially when dealing with spatial data or when specific orientations of data are required.


In [ ]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flipping the array left to right
flipped_array = np.fliplr(array_2d)

print("Original 2D array:\n", array_2d)
print("\nFlipped left to right 2D array:\n", flipped_array)

#### 6.10 **np.mean() / np.median / ...**

NumPy provides several functions to calculate various types of averages (measures of central tendency) for arrays. These functions are optimized for performance on numerical data and are widely used in statistics and data analysis.

- **`np.mean()`**: Computes the arithmetic mean (average) of the array elements.
$$
\text{np.mean(a, axis=None)}
$$
Where:
- `a`: the input array.
- `axis`: the axis along which the means are computed (optional).

- **`np.median()`**: Computes the median of the array elements. The median is the middle value in a sorted list of numbers.
$$
\text{np.median(a, axis=None)}
$$
Where:
- `a`: the input array.
- `axis`: the axis along which the medians are computed (optional).

- **`np.average()`**: Computes the weighted average of the array elements along a specified axis.
$$
\text{np.average(a, axis=None, weights=None)}
$$
Where:
- `a`: the input array.
- `axis`: the axis along which the average is computed (optional).
- `weights`: An array of weights associated with the values in `a` (optional).

These functions are essential for summarizing and understanding the distribution of data in NumPy arrays.

In [ ]:
# Creating an array
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculating the mean
mean_value = np.mean(data)
print("Mean:", mean_value)

# Calculating the median
median_value = np.median(data)
print("Median:", median_value)

# Calculating the weighted average
weights = np.array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2]) # Example weights
weighted_average = np.average(data, weights=weights)
print("Weighted Average:", weighted_average)

# Calculating mean along an axis for a 2D array
data_2d = np.array([[1, 2, 3], [4, 5, 6]])
mean_axis_0 = np.mean(data_2d, axis=0) # Mean of each column
mean_axis_1 = np.mean(data_2d, axis=1) # Mean of each row

print("\nOriginal 2D array:\n", data_2d)
print("\nMean along axis 0 (columns):", mean_axis_0)
print("Mean along axis 1 (rows):", mean_axis_1)

Mean: 5.5
Median: 5.5
Weighted Average: 6.333333333333333

Original 2D array:
 [[1 2 3]
 [4 5 6]]

Mean along axis 0 (columns): [2.5 3.5 4.5]
Mean along axis 1 (rows): [2. 5.]
