In [ ]:
# @title
from IPython.display import display, HTML

display(HTML("""
<script>
const firstCell = document.querySelector('.cell.code_cell');
if (firstCell) {
  firstCell.querySelector('.input').style.pointerEvents = 'none';
  firstCell.querySelector('.input').style.opacity = '0.5';
}
</script>
"""))

html = """
<div style="display:flex; flex-direction:column; align-items:center; text-align:center; gap:12px; padding:8px;">
  <h1 style="margin:0;">👋 Welcome to <span style="color:#1E88E5;">Algopath Coding Academy</span>!</h1>

  <img src="https://raw.githubusercontent.com/sshariqali/mnist_pretrained_model/main/algopath_logo.jpg"
       alt="Algopath Coding Academy Logo"
       width="400"
       style="border-radius:15px; box-shadow:0 4px 12px rgba(0,0,0,0.2); max-width:100%; height:auto;" />

  <p style="font-size:16px; margin:0;">
    <em>Empowering young minds to think creatively, code intelligently, and build the future with AI.</em>
  </p>
</div>
"""

display(HTML(html))

# PyTorch Tensors Tutorial


**Table of Contents:**
1. [Introduction to PyTorch](#1)
2. [Creating Tensors](#2)
3. [Tensor Attributes and Properties](#3)
4. [Tensor Indexing Slicing and Filtering](#4)
5. [Tensor Operations](#5)
6. [Tensor Manipulation](#6)
7. [GPU Interaction](#7)
8. [NumPy vs PyTorch Comparison](#8)

---

<a name='1'></a>
## **1. Introduction to PyTorch Tensors**

### What is PyTorch?
PyTorch is an open-source deep learning library developed by Facebook's AI Research lab. It provides:
- Tensor computation with strong GPU acceleration
- Automatic differentiation for building neural networks
- A flexible and intuitive API for research and production

### What is a Tensor?
A **tensor** is the core data structure in PyTorch. Think of it as:
- Similar to a NumPy `ndarray` but with additional capabilities
- Can run on GPUs for accelerated computing
- Supports automatic differentiation (autograd) for neural network training
- A multi-dimensional array that can represent scalars, vectors, matrices, and higher-dimensional data

### Importing PyTorch

In [1]:
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")

PyTorch version: 2.9.0+cpu


### Setting up your Device
Check if CUDA (GPU) is available and set the device accordingly:

In [2]:
# Check if CUDA is available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

if device == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available, using CPU")

Using device: cpu
GPU not available, using CPU


---
<a name='2'></a>
## **2. Creating Tensors**

### From Existing Data

In [ ]:
# Using torch.tensor() - from Python lists or tuples
tensor_1d = torch.tensor([9, 12, 25, 5, 10])
tensor_1d

tensor([ 9, 11, 25,  5, 10])

In [ ]:
# 2D tensor from nested list
tensor_2d = torch.tensor([[9, 12, 25], [5, 10, 16]])
tensor_2d

tensor([[ 9, 11, 25],
        [ 5, 10, 16]])

In [6]:
# Using torch.from_numpy() - from NumPy array (shares memory!)
np_array = np.array([12, 15, 20, 25])
tensor_from_numpy = torch.from_numpy(np_array)
tensor_from_numpy

tensor([12, 15, 20, 25])

### Creating New Tensors

In [7]:
# torch.zeros()
zeros_tensor = torch.zeros(3, 4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
# torch.ones()
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# torch.rand() - uniform distribution [0, 1)
# random values between 0 and 1. Uniform distribution means all values are equally likely.
rand_uniform = torch.rand(3, 3)
rand_uniform

tensor([[0.4664, 0.7369, 0.1835],
        [0.0862, 0.5104, 0.5799],
        [0.4217, 0.7657, 0.9702]])

In [14]:
# torch.arange() - sequence of values
arange_tensor = torch.arange(0, 10, 2)
arange_tensor

tensor([0, 2, 4, 6, 8])

In [17]:
# torch.linspace() - linearly spaced values
linspace_tensor = torch.linspace(0, 1, 5)
linspace_tensor

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

---
<a name='3'></a>
## **3. Tensor Attributes and Properties**

In [5]:
# Create a sample tensor
sample_tensor = torch.randn(2, 2)
sample_tensor

tensor([[-0.0762, -2.4215],
        [-0.2484,  2.1531]])

In [6]:
# Data type
sample_tensor.dtype

torch.float32

In [7]:
# Shape
sample_tensor.shape # sample_tensor.size()

torch.Size([2, 2])

In [ ]:
# Check which device the tensor is on
print(sample_tensor.device)

# Move tensor to GPU if available
if torch.cuda.is_available():
    sample_tensor = sample_tensor.to('cuda')
    print(sample_tensor.device)

device(type='cpu')

In [9]:
# Number of dimensions
sample_tensor.ndim

2

In [10]:
# Total number of elements
sample_tensor.numel()

4

In [12]:
# Create tensors with specific dtypes
int_tensor = torch.tensor([1, 2, 3], dtype = torch.long)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype = torch.float32)
print(f"Integer tensor dtype: {int_tensor.dtype}")
print(f"Float tensor dtype: {float_tensor.dtype}")

Integer tensor dtype: torch.int64
Float tensor dtype: torch.float32


---
<a name='4'></a>
## **4. Tensor Indexing, Slicing, and Filtering**

In [7]:
# Create a sample tensor for indexing
tensor = torch.rand(4,6)
tensor

tensor([[0.9053, 0.4043, 0.8561, 0.9175, 0.5014, 0.3896],
        [0.7273, 0.0145, 0.2873, 0.4997, 0.3504, 0.0737],
        [0.4426, 0.2325, 0.9622, 0.5124, 0.3272, 0.6838],
        [0.7561, 0.8080, 0.8834, 0.0447, 0.2182, 0.7886]])

In [30]:
# Standard indexing
tensor[0, 0] # Access element at row 0, column 0

tensor(0)

In [33]:
# Accessing rows and columns
tensor[0] # First row
# tensor[:, 1] # Second column

tensor([0, 1, 2, 3, 4, 5])

In [34]:
# Slicing
tensor[0:2] # First 2 rows

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [35]:
tensor[1:3, 2:4] # Rows 1-3, Columns 2-4

tensor([[ 8,  9],
        [14, 15]])

In [36]:
tensor[::2] # Every other row

tensor([[ 0,  1,  2,  3,  4,  5],
        [12, 13, 14, 15, 16, 17]])

In [37]:
# Boolean/Masked indexing
mask = tensor > 10
print("Boolean mask (elements > 10):") # 
print(mask) # boolean mask retains the original tensor's shape
print("\nFiltered values (> 10):")
print(tensor[mask]) # filtered values are a 1D array of only the elements that meet the condition.

Boolean mask (elements > 10):
tensor([[False, False, False, False, False, False],
        [False, False, False, False, False,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True]])

Filtered values (> 10):
tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])


In [38]:
# torch.where() - conditional selection
result = torch.where(tensor > 10, tensor, torch.tensor(0)) # replace values <= 10 with 0
result

tensor([[ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

---
<a name='5'></a>
## **5. Tensor Operations**

### Element-wise Arithmetic

In [16]:
# Create sample tensors
a = torch.rand((3,3))
b = torch.rand((3,3))

print("Tensor a:\n", a)
print("Tensor b:\n", b)

Tensor a:
 tensor([[0.0917, 0.6345, 0.2946],
        [0.9469, 0.7935, 0.1982],
        [0.5007, 0.8374, 0.3373]])
Tensor b:
 tensor([[0.8797, 0.4347, 0.7658],
        [0.9362, 0.6688, 0.9601],
        [0.4063, 0.5270, 0.3932]])


In [17]:
# Addition
a + b # or torch.add(a, b)

tensor([[0.9714, 1.0692, 1.0604],
        [1.8831, 1.4624, 1.1583],
        [0.9070, 1.3644, 0.7305]])

In [18]:
# Subtraction
a - b # or torch.sub(a, b)

tensor([[-0.7880,  0.1997, -0.4711],
        [ 0.0107,  0.1247, -0.7618],
        [ 0.0944,  0.3104, -0.0558]])

In [19]:
# Multiplication (element-wise)
a * b # or torch.mul(a, b)

tensor([[0.0807, 0.2758, 0.2256],
        [0.8865, 0.5307, 0.1903],
        [0.2034, 0.4413, 0.1326]])

In [22]:
# Division
a / b # or torch.div(a, b)

tensor([[0.1042, 1.4595, 0.3847],
        [1.0114, 1.1865, 0.2065],
        [1.2324, 1.5890, 0.8580]])

In [23]:
# Power
a ** 2 # or torch.pow(a, 2)

tensor([[0.0084, 0.4026, 0.0868],
        [0.8966, 0.6297, 0.0393],
        [0.2507, 0.7012, 0.1138]])

In [24]:
# Scalar operations
scalar = 2.0
a + scalar

tensor([[2.0917, 2.6345, 2.2946],
        [2.9469, 2.7935, 2.1982],
        [2.5007, 2.8374, 2.3373]])

### In-place Operations
Operations ending with `_` modify the tensor in-place:

In [25]:
# In-place addition
a.add_(5)
a

tensor([[5.0917, 5.6345, 5.2946],
        [5.9469, 5.7935, 5.1982],
        [5.5007, 5.8374, 5.3373]])

In [28]:
# In-place multiplication
a.subtract_(3)
a

# Note: In-place operations save memory but modify the original tensor
# Regular operations create new tensors

tensor([[0.0917, 0.6345, 0.2946],
        [0.9469, 0.7935, 0.1982],
        [0.5007, 0.8374, 0.3373]])

### Matrix Operations

In [29]:
# Matrix multiplication
mat1 = torch.tensor([[10, 6], [25, 13]])
mat2 = torch.tensor([[19, 45], [16, 2]])

print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)

Matrix 1:
 tensor([[10,  6],
        [25, 13]])
Matrix 2:
 tensor([[19, 45],
        [16,  2]])


In [30]:
# Matrix multiplication using torch.matmul()
result1 = torch.matmul(mat1, mat2)
result1

tensor([[ 286,  462],
        [ 683, 1151]])

In [31]:
# Matrix multiplication using @ operator
result2 = mat1 @ mat2
result2

tensor([[ 286,  462],
        [ 683, 1151]])

In [32]:
# Transpose
mat1.transpose(0, 1)  # Swap dimensions 0 and 1 
# torch.transpose(mat, 0, 1)  # Alternative method

tensor([[10, 25],
        [ 6, 13]])

In [33]:
mat1.T # Shortcut for transpose for 2D tensors

tensor([[10, 25],
        [ 6, 13]])

### Reduction Operations

In [37]:
# Create a sample tensor
tensor = torch.tensor([[10, 6, 25],
                       [13, 19, 45],
                       [16, 2, 11]], dtype=torch.float)
tensor

tensor([[10.,  6., 25.],
        [13., 19., 45.],
        [16.,  2., 11.]])

In [38]:
# Sum
torch.sum(tensor)
torch.sum(tensor, dim = 0) # Sum along columns
torch.sum(tensor, dim = 1) # Sum along rows

tensor([41., 77., 29.])

In [39]:
# Mean
torch.mean(tensor)
torch.mean(tensor, dim=0)

tensor([13.,  9., 27.])

In [41]:
# Standard deviation
torch.std(tensor, dim=1)

tensor([10.0167, 17.0098,  7.0946])

In [ ]:
# Max and Min
torch.max(tensor) # along dimension can be specified as well by torch.max(tensor, dim=0)
torch.min(tensor) # along dimension can be specified as well by torch.min(tensor, dim=0)

In [ ]:
# Argmax (index of maximum value)
torch.argmax(tensor)
torch.argmax(tensor, dim=0)
torch.argmax(tensor, dim=1)

### Broadcasting
Broadcasting allows operations between tensors of different shapes:

In [47]:
# Broadcasting examples
a = torch.tensor([[10, 6, 25],
                  [13, 19, 45]])
b = torch.tensor([16, 12, 11])

print("Tensor a:")
print(a)
print(a.shape)
print("\nTensor b:")
print(b)
print(b.shape)

Tensor a:
tensor([[10,  6, 25],
        [13, 19, 45]])
torch.Size([2, 3])

Tensor b:
tensor([16, 12, 11])
torch.Size([3])


In [48]:
# Broadcasting: b is automatically expanded to match a's shape
result = a + b
print("\nBroadcasted addition (a + b):")
print(result)


Broadcasted addition (a + b):
tensor([[26, 18, 36],
        [29, 31, 56]])


---
<a name='6'></a>
## **6. Tensor Manipulation (Reshaping)**

### Reshaping Tensors

In [53]:
# Create a sample tensor
tensor = torch.arange(11, 23)
tensor

tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [54]:
tensor.shape

torch.Size([12])

In [57]:
# Reshaping to (3, 4)
reshaped_tensor = torch.reshape(tensor, (3, 4))
reshaped_tensor

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]])

In [58]:
reshaped_tensor.shape

torch.Size([3, 4])

In [61]:
# .view() - returns a view (must be contiguous)
viewed = tensor.view(3, 4)
viewed

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]])

In [62]:
viewed.shape

torch.Size([3, 4])

**Difference Between `.view()` and `.reshape()` (Explained Simply)**

<div align="center">
  <img src="https://i.sstatic.net/ee7Hj.png" width="500"/>
  <p><i>Tensor and its underlying storage</i></p>
</div>

<div align="center">
  <img src="https://i.sstatic.net/26Q9g.png" width="500"/>
  <p><i>The right-hand tensor (shape (3,2)) can be computed from the left-hand one with t2 = t1.view(3,2)</i></p>
</div>

A View is like a different "lens" looking at the same data. It doesn't create new data in your RAM or GPU memory; it just changes the metadata (shape and strides) about how to read that data.

**What is `.view()`?**
- `.view()` changes the shape of a tensor **without copying the data**.
- It only works if the tensor's data is stored in a **contiguous block** in memory (all elements are lined up in order).
- If the tensor is **not contiguous** (for example, after a transpose), `.view()` will give an error.

**What is `.reshape()`?**
- `.reshape()` also changes the shape of a tensor.
- If possible, it returns a **view** (no copy, just like `.view()`).
- If the tensor is **not contiguous**, `.reshape()` will **make a copy** of the data so it can still give you the new shape.
- So, `.reshape()` is more flexible and works in more situations.

**What does "contiguous" mean?**
- **Contiguous**: All the elements of the tensor are stored in memory one after another, in the order you see them.
- **Non-contiguous**: The elements are not stored in order (for example, after you transpose a tensor, the way data is stored in memory changes).

**When to use `.view()`?**
- Use `.view()` when you are sure your tensor is **contiguous** (hasn't been transposed or sliced in a way that changes memory order).
- It's a bit faster because it never copies data.

**When to use `.reshape()`?**
- Use `.reshape()` if you are **not sure** if your tensor is contiguous.
- It will work in more cases, but might copy data if needed.

In [51]:
x = torch.arange(6).view(2, 3)
print(f"Original x:\n{x}")
print(f"Is x contiguous? {x.is_contiguous()}") # True

# 2. Transpose the tensor
# Memory still looks like: [0, 1, 2, 3, 4, 5]
# But the "instructions" say to read it vertically.
xt = x.transpose(0, 1)
print(f"\nTransposed x:\n{xt}")
print(f"Is transposed contiguous? {xt.is_contiguous()}") # False

# 3. Try to use .view()
try:
    print("\nAttempting xt.view(6)...")
    xt.view(6)
except RuntimeError as e:
    print(f"Error: {e}")

# 4. Make it contiguous and then use .view()
print("\nMaking xt contiguous and then viewing...")
xt_contiguous = xt.contiguous()
xt_contiguous.view(6)

Original x:
tensor([[0, 1, 2],
        [3, 4, 5]])
Is x contiguous? True

Transposed x:
tensor([[0, 3],
        [1, 4],
        [2, 5]])
Is transposed contiguous? False

Attempting xt.view(6)...
Error: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

Making xt contiguous and then viewing...


tensor([0, 3, 1, 4, 2, 5])

In [15]:
# Using -1 to infer dimension
auto_reshape = tensor.view(3, -1)
auto_reshape

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Changing Dimensions

In [17]:
# torch.squeeze() - remove dimensions of size 1
tensor_4d = torch.randn(1, 3, 1, 4)
tensor_4d

tensor([[[[ 0.2423, -1.6811,  0.0700, -1.1526]],

         [[-0.3222,  0.5486,  1.5061, -0.8805]],

         [[ 0.1760,  0.7252, -0.1779, -0.3199]]]])

In [18]:
tensor_4d.shape

torch.Size([1, 3, 1, 4])

In [19]:
squeezed = torch.squeeze(tensor_4d)
squeezed

tensor([[ 0.2423, -1.6811,  0.0700, -1.1526],
        [-0.3222,  0.5486,  1.5061, -0.8805],
        [ 0.1760,  0.7252, -0.1779, -0.3199]])

In [20]:
squeezed.shape

torch.Size([3, 4])

In [21]:
# Squeeze specific dimension
squeezed_dim = torch.squeeze(tensor_4d, dim = 0)
squeezed_dim.shape

torch.Size([3, 1, 4])

In [24]:
# torch.unsqueeze() - add a dimension of size 1
unsqueezed_0 = torch.unsqueeze(squeezed_dim, dim = 0)
unsqueezed_0.shape

torch.Size([1, 3, 1, 4])

In [25]:
# torch.unsqueeze() - add a dimension of size 1
unsqueezed_0 = torch.unsqueeze(squeezed_dim, dim = 1)
unsqueezed_0.shape

torch.Size([3, 1, 1, 4])

### Combining Tensors

In [ ]:
# torch.cat() - concatenate along an existing dimension
a = torch.tensor([[10, 6], [25, 13]])
b = torch.tensor([[9, 45], [17, 26]])

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)

Tensor a:
tensor([[10,  6],
        [25, 13]])

Tensor b:
tensor([[ 9, 45],
        [17, 26]])


In [64]:
# Concatenate along dimension 0 (rows)
cat_dim0 = torch.cat([a, b], dim=0)
cat_dim0

tensor([[10,  6],
        [25, 13],
        [ 9, 45],
        [17, 26]])

In [65]:
# Concatenate along dimension 1 (columns)
cat_dim1 = torch.cat([a, b], dim=1)
cat_dim1

tensor([[10,  6,  9, 45],
        [25, 13, 17, 26]])

In [73]:
# torch.stack() - stack along a new dimension
stacked_dim0 = torch.stack([a, b], dim = 0) # 0 means row wise stacking and 1 means column wise stacking
stacked_dim0

tensor([[[10,  6],
         [25, 13]],

        [[ 9, 45],
         [17, 26]]])

In [72]:
stacked_dim0.shape

torch.Size([2, 2, 2])

### Splitting Tensors

In [38]:
# Create a tensor to split
tensor = torch.arange(12).reshape(3, 4)
tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [39]:
tensor.shape

torch.Size([3, 4])

In [43]:
# torch.split() - split into chunks of a given size
splits = torch.split(tensor, 2, dim=0)
splits

(tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 tensor([[ 8,  9, 10, 11]]))

In [44]:
# torch.chunk() - split into a specific number of chunks
chunks = torch.chunk(tensor, 2, dim=1)
chunks

(tensor([[0, 1],
         [4, 5],
         [8, 9]]),
 tensor([[ 2,  3],
         [ 6,  7],
         [10, 11]]))

### Reordering Dimensions

| Operation         | Resulting Tensor                | Logic/Explanation                                      |
|-------------------|---------------------------------|--------------------------------------------------------|
| **Original**      | <pre>[[1, 2, 3],<br> [4, 5, 6]]</pre> <br>Shape: (2, 3) | Starting tensor                                        |
| `reshape(3, 2)`   | <pre>[[1, 2],<br> [3, 4],<br> [5, 6]]</pre> | Fills the new shape sequentially: 1, 2, then 3, 4, etc.|
| `permute(1, 0)`   | <pre>[[1, 4],<br> [2, 5],<br> [3, 6]]</pre> | Swaps axes: Row 1 becomes Column 1, etc.               |

**Key Difference:**
- `reshape` changes the shape by reordering the elements in memory sequentially.
- `permute` changes the order of axes (dimensions) without changing the order of elements in memory.

In [74]:
tensor = torch.rand(2,3)
tensor.shape

torch.Size([2, 3])

In [75]:
tensor

tensor([[0.3119, 0.5794, 0.5553],
        [0.8826, 0.4619, 0.9928]])

In [76]:
# Permute dimensions works by reordering the dimensions of a tensor to a specified order.
permuted = tensor.permute(1, 0)
permuted.shape

torch.Size([3, 2])

In [77]:
permuted

tensor([[0.3119, 0.8826],
        [0.5794, 0.4619],
        [0.5553, 0.9928]])

In [78]:
reshaped = tensor.reshape(3, 2)
reshaped.shape

torch.Size([3, 2])

In [79]:
reshaped

tensor([[0.3119, 0.5794],
        [0.5553, 0.8826],
        [0.4619, 0.9928]])

---
<a name='7'></a>
## **7. NumPy & GPU Interaction**

### Moving Tensors Between CPU and GPU

In [9]:
# Create a CPU tensor
cpu_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0])
print("CPU Tensor:", cpu_tensor)
print("Device:", cpu_tensor.device)

CPU Tensor: tensor([1., 2., 3., 4.])
Device: cpu


In [ ]:
# Create a GPU tensor (if CUDA is available)
gpu_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0], device = 'cuda')
print("GPU Tensor:", gpu_tensor)
print("Device:", gpu_tensor.device)

GPU Tensor: tensor([1., 2., 3., 4.], device='cuda:0')
Device: cuda:0


### NumPy Bridge

In [ ]:
# Convert Tensor to NumPy (only works on CPU tensors)

np_from_tensor = cpu_tensor.numpy()
print("NumPy from tensor:", np_from_tensor)


Tensor: tensor([10., 20., 30., 40.])
NumPy from tensor: [10. 20. 30. 40.]


---
<a name='8'></a>
## **8. Benefits of PyTorch over NumPy**

### Why PyTorch for Machine Learning? Key Benefits

PyTorch offers several advantages over NumPy for machine learning tasks:

#### 1. **GPU Acceleration**
- PyTorch tensors can seamlessly move between CPU and GPU
- Massive speedup for large-scale computations (10-100x faster)
- Essential for training deep neural networks

#### 2. **Automatic Differentiation (Autograd)**
- Automatically computes gradients for backpropagation
- Critical for training neural networks
- No need to manually derive and implement gradient calculations

#### 3. **Built for Deep Learning**
- Rich ecosystem of neural network layers, optimizers, and loss functions
- Easy model building with `torch.nn` module
- Pre-trained models and transfer learning support

#### 4. **Strong Community and Ecosystem**
- Extensive libraries (torchvision, torchaudio, etc.)
- Active research community
- Excellent documentation and tutorials

### Demonstration: GPU Speedup

In [3]:
import time

In [4]:
# Large matrix multiplication comparison
size = 5000

In [5]:
# NumPy (CPU only)
np_a = np.random.randn(size, size)
np_b = np.random.randn(size, size)

In [6]:
# PyTorch CPU
torch_a_cpu = torch.randn(size, size)
torch_b_cpu = torch.randn(size, size)

In [7]:
# PyTorch GPU
torch_a_gpu = torch.randn(size, size).to('cuda')
torch_b_gpu = torch.randn(size, size).to('cuda')

In [8]:
start = time.time()
np_result = np.dot(np_a, np_b)
np_time = time.time() - start

print(f"NumPy (CPU) time: {np_time:.4f} seconds")

NumPy (CPU) time: 4.6320 seconds


In [9]:
start = time.time()
torch_result_cpu = torch_a_cpu @ torch_b_cpu
torch_cpu_time = time.time() - start

print(f"PyTorch (CPU) time: {torch_cpu_time:.4f} seconds")

PyTorch (CPU) time: 2.1483 seconds


In [10]:
start = time.time()
torch_result_gpu = torch_a_gpu @ torch_b_gpu
torch_gpu_time = time.time() - start

print(f"PyTorch (GPU) time: {torch_gpu_time:.4f} seconds")

PyTorch (GPU) time: 0.1555 seconds


In [ ]:
# # PyTorch GPU (if available)
# if torch.cuda.is_available():
#     torch_a_gpu = torch.randn(size, size).to(device)
#     torch_b_gpu = torch.randn(size, size).to(device)

#     # Warm up GPU
#     _ = torch.matmul(torch_a_gpu, torch_b_gpu)
#     torch.cuda.synchronize()

#     start = time.time()
#     torch_result_gpu = torch.matmul(torch_a_gpu, torch_b_gpu)
#     torch.cuda.synchronize()
#     torch_gpu_time = time.time() - start

#     print(f"PyTorch (GPU) time: {torch_gpu_time:.4f} seconds")
#     print(f"\n🚀 GPU Speedup: {torch_cpu_time / torch_gpu_time:.2f}x faster than CPU")
# else:
#     print("\n⚠️ GPU not available for speed comparison")

### When to Use What?

**Use NumPy when:**
- Doing general numerical computations
- Working with small to medium datasets
- Not training neural networks
- CPU processing is sufficient

**Use PyTorch when:**
- Building and training neural networks
- Need GPU acceleration
- Require automatic differentiation
- Working on deep learning projects
- Need production deployment of ML models

---
<a name='9'></a>
## **9. Reading Material**

### **torch.rand() vs torch.randn()**

<div align="center">
  <img src="https://i-blog.csdnimg.cn/direct/e34944beb690439b8505f2bba367b7cc.png" width="700"/>
  <p><i>Uniform Distribution vs Normal Distribution</i></p>
</div>

In [ ]:
# torch.rand() - uniform distribution [0, 1)
# random values between 0 and 1. Uniform distribution means all values are equally likely.
rand_uniform = torch.rand(3, 3)
rand_uniform

In [ ]:
# torch.randn() - standard normal distribution (mean=0, std=1)
# random values from a normal distribution with mean 0 and standard deviation 1. 
# 68.3 % probability that values are between -1 and 1
# 95.4 % probability that values are between -2 and 2
# range is theoretically from -infinity to +infinity.

rand_normal = torch.randn(3, 3)
rand_normal

## Conclusion

In this tutorial, you've learned:

1. ✅ What PyTorch is and why it's essential for deep learning
2. ✅ How to create tensors in various ways
3. ✅ Tensor attributes and properties
4. ✅ Indexing, slicing, and filtering tensors
5. ✅ Essential tensor operations (arithmetic, matrix ops, reductions)
6. ✅ Tensor manipulation (reshaping, combining, splitting)
7. ✅ NumPy integration and GPU acceleration
8. ✅ Key differences between NumPy and PyTorch
9. ✅ Why PyTorch is superior for machine learning

### Next Steps

- Explore PyTorch's autograd in depth
- Learn about `torch.nn` for building neural networks
- Practice with real datasets using `torch.utils.data`
- Implement your first neural network!

**Happy Learning! 🚀**