In [ ]:
# @title
from IPython.display import display, HTML

display(HTML("""
<script>
const firstCell = document.querySelector('.cell.code_cell');
if (firstCell) {
  firstCell.querySelector('.input').style.pointerEvents = 'none';
  firstCell.querySelector('.input').style.opacity = '0.5';
}
</script>
"""))

html = """
<div style="display:flex; flex-direction:column; align-items:center; text-align:center; gap:12px; padding:8px;">
  <h1 style="margin:0;">👋 Welcome to <span style="color:#1E88E5;">Algopath Coding Academy</span>!</h1>

  <img src="https://raw.githubusercontent.com/sshariqali/mnist_pretrained_model/main/algopath_logo.jpg"
       alt="Algopath Coding Academy Logo"
       width="400"
       style="border-radius:15px; box-shadow:0 4px 12px rgba(0,0,0,0.2); max-width:100%; height:auto;" />

  <p style="font-size:16px; margin:0;">
    <em>Empowering young minds to think creatively, code intelligently, and build the future with AI.</em>
  </p>
</div>
"""

display(HTML(html))

# PyTorch Tensors Tutorial


**Table of Contents:**
1. [Introduction to PyTorch](#1)
2. [Creating Tensors](#2)
3. [Tensor Attributes and Properties](#3)
4. [Tensor Indexing Slicing and Filtering](#4)
5. [Tensor Operations](#5)
6. [Tensor Manipulation](#6)
7. [GPU Interaction](#7)
8. [NumPy vs PyTorch Comparison](#8)

---

<a name='1'></a>
## **1. Introduction to PyTorch Tensors**

### What is PyTorch?
PyTorch is an open-source deep learning library developed by Facebook's AI Research lab. It provides:
- Tensor computation with strong GPU acceleration
- Automatic differentiation for building neural networks
- A flexible and intuitive API for research and production

### What is a Tensor?
A **tensor** is the core data structure in PyTorch. Think of it as:
- Similar to a NumPy `ndarray` but with additional capabilities
- Can run on GPUs for accelerated computing
- Supports automatic differentiation (autograd) for neural network training
- A multi-dimensional array that can represent scalars, vectors, matrices, and higher-dimensional data

### Importing PyTorch

In [1]:
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")

PyTorch version: 2.9.0+cpu


### Setting up your Device
Check if CUDA (GPU) is available and set the device accordingly:

In [2]:
# Check if CUDA is available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

if device == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available, using CPU")

Using device: cpu
GPU not available, using CPU


---
<a name='2'></a>
## **2. Creating Tensors**

### From Existing Data

In [4]:
# Using torch.tensor() - from Python lists or tuples
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
tensor_1d

tensor([1, 2, 3, 4, 5])

In [5]:
# 2D tensor from nested list
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
# Using torch.from_numpy() - from NumPy array (shares memory!)
np_array = np.array([1.0, 2.0, 3.0, 4.0])
tensor_from_numpy = torch.from_numpy(np_array)
tensor_from_numpy

tensor([1., 2., 3., 4.], dtype=torch.float64)

### Creating New Tensors

In [7]:
# torch.zeros()
zeros_tensor = torch.zeros(3, 4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
# torch.ones()
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# torch.rand() - uniform distribution [0, 1)
# random values between 0 and 1. Uniform distribution means all values are equally likely.
rand_uniform = torch.rand(3, 3)
rand_uniform

tensor([[0.4664, 0.7369, 0.1835],
        [0.0862, 0.5104, 0.5799],
        [0.4217, 0.7657, 0.9702]])

In [13]:
# torch.randn() - standard normal distribution (mean=0, std=1)
# random values from a normal distribution with mean 0 and standard deviation 1. range is theoretically from -infinity to +infinity.
rand_normal = torch.randn(3, 3)
rand_normal

tensor([[ 0.3455, -0.2079, -0.3835],
        [-1.4898, -0.1833, -0.1595],
        [-0.1620,  0.7861, -0.4565]])

In [14]:
# torch.arange() - sequence of values
arange_tensor = torch.arange(0, 10, 2)
arange_tensor

tensor([0, 2, 4, 6, 8])

In [17]:
# torch.linspace() - linearly spaced values
linspace_tensor = torch.linspace(0, 1, 5)
linspace_tensor

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

### Creating Tensors Based on Other Tensors

In [18]:
# Create a reference tensor
reference_tensor = torch.rand(2, 3)
reference_tensor

tensor([[0.1664, 0.4794, 0.7029],
        [0.7985, 0.4445, 0.1382]])

In [19]:
# torch.zeros_like()
zeros_like = torch.zeros_like(reference_tensor)
zeros_like

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
# torch.ones_like()
ones_like = torch.ones_like(reference_tensor)
ones_like

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
# torch.rand_like()
rand_like = torch.rand_like(reference_tensor)
rand_like

tensor([[0.6724, 0.6249, 0.4836],
        [0.8151, 0.1190, 0.2250]])

---
<a name='3'></a>
## **3. Tensor Attributes and Properties**

In [5]:
# Create a sample tensor
sample_tensor = torch.randn(2, 2)
sample_tensor

tensor([[-0.0762, -2.4215],
        [-0.2484,  2.1531]])

In [6]:
# Data type
sample_tensor.dtype

torch.float32

In [7]:
# Shape
sample_tensor.shape # sample_tensor.size()

torch.Size([2, 2])

In [ ]:
# Device
sample_tensor.device

# Move tensor to GPU if available
if torch.cuda.is_available():
    sample_tensor = sample_tensor.to('cuda')
    sample_tensor.device

device(type='cpu')

In [9]:
# Number of dimensions
sample_tensor.ndim

2

In [10]:
# Total number of elements
sample_tensor.numel()

4

In [12]:
# Create tensors with specific dtypes
int_tensor = torch.tensor([1, 2, 3], dtype = torch.long)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype = torch.float32)
print(f"Integer tensor dtype: {int_tensor.dtype}")
print(f"Float tensor dtype: {float_tensor.dtype}")

Integer tensor dtype: torch.int64
Float tensor dtype: torch.float32


---
<a name='4'></a>
## **4. Tensor Indexing, Slicing, and Filtering**

In [17]:
# Create a sample tensor for indexing
tensor = torch.arange(24).reshape(4, 6)
tensor

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [30]:
# Standard indexing
tensor[0, 0] # Access element at row 0, column 0

tensor(0)

In [33]:
# Accessing rows and columns
tensor[0] # First row
# tensor[:, 1] # Second column

tensor([0, 1, 2, 3, 4, 5])

In [34]:
# Slicing
tensor[0:2] # First 2 rows

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [35]:
tensor[1:3, 2:4] # Rows 1-3, Columns 2-4

tensor([[ 8,  9],
        [14, 15]])

In [36]:
tensor[::2] # Every other row

tensor([[ 0,  1,  2,  3,  4,  5],
        [12, 13, 14, 15, 16, 17]])

In [37]:
# Boolean/Masked indexing
mask = tensor > 10
print("Boolean mask (elements > 10):") # 
print(mask) # boolean mask retains the original tensor's shape
print("\nFiltered values (> 10):")
print(tensor[mask]) # filtered values are a 1D array of only the elements that meet the condition.

Boolean mask (elements > 10):
tensor([[False, False, False, False, False, False],
        [False, False, False, False, False,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True]])

Filtered values (> 10):
tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])


In [38]:
# torch.where() - conditional selection
result = torch.where(tensor > 10, tensor, torch.tensor(0)) # replace values <= 10 with 0
result

tensor([[ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

---
<a name='5'></a>
## **5. Tensor Operations**

### Element-wise Arithmetic

In [40]:
# Create sample tensors
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("Tensor a:", a)
print("Tensor b:", b)

Tensor a: tensor([1., 2., 3.])
Tensor b: tensor([4., 5., 6.])


In [ ]:
# Addition
a + b # or torch.add(a, b)

tensor([5., 7., 9.])

In [ ]:
# Subtraction
a - b # or torch.sub(a, b)

In [ ]:
# Multiplication (element-wise)
a * b # or torch.mul(a, b)

In [ ]:
# Division
a / b # or torch.div(a, b)

tensor([0.2500, 0.4000, 0.5000])

In [45]:
# Power
a ** 2 # or torch.pow(a, 2)

tensor([1., 4., 9.])

In [46]:
# Scalar operations
scalar = 2.0
a + scalar

tensor([3., 4., 5.])

### In-place Operations
Operations ending with `_` modify the tensor in-place:

In [47]:
# In-place operations (methods ending with _)
x = torch.tensor([1.0, 2.0, 3.0])
x

tensor([1., 2., 3.])

In [48]:
# In-place addition
x.add_(5)
x

tensor([6., 7., 8.])

In [49]:
# In-place multiplication
x.mul_(2)
x

# Note: In-place operations save memory but modify the original tensor
# Regular operations create new tensors

tensor([12., 14., 16.])

### Matrix Operations

In [50]:
# Matrix multiplication
mat1 = torch.tensor([[1, 2], [3, 4]])
mat2 = torch.tensor([[5, 6], [7, 8]])

print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)

Matrix 1:
 tensor([[1, 2],
        [3, 4]])
Matrix 2:
 tensor([[5, 6],
        [7, 8]])


In [51]:
# Matrix multiplication using torch.matmul()
result1 = torch.matmul(mat1, mat2)
result1

tensor([[19, 22],
        [43, 50]])

In [52]:
# Matrix multiplication using @ operator
result2 = mat1 @ mat2
result2

tensor([[19, 22],
        [43, 50]])

In [55]:
# Transpose
mat1.transpose(0, 1)  # Swap dimensions 0 and 1 
# torch.transpose(mat, 0, 1)  # Alternative method

tensor([[1, 3],
        [2, 4]])

In [57]:
mat1.T # Shortcut for transpose for 2D tensors

tensor([[1, 3],
        [2, 4]])

### Reduction Operations

In [58]:
# Create a sample tensor
tensor = torch.tensor([[1.0, 2.0, 3.0],
                       [4.0, 5.0, 6.0],
                       [7.0, 8.0, 9.0]])
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [60]:
# Sum
torch.sum(tensor)
torch.sum(tensor, dim = 0) # Sum along columns
torch.sum(tensor, dim = 1) # Sum along rows

tensor([ 6., 15., 24.])

In [ ]:
# Mean
torch.mean(tensor)
torch.mean(tensor, dim=0)

In [ ]:
# Standard deviation
torch.std(tensor)

In [ ]:
# Max and Min
torch.max(tensor) # along dimension can be specified as well by torch.max(tensor, dim=0)
torch.min(tensor) # along dimension can be specified as well by torch.min(tensor, dim=0)

In [ ]:
# Argmax (index of maximum value)
torch.argmax(tensor)
torch.argmax(tensor, dim=0)
torch.argmax(tensor, dim=1)

### Broadcasting
Broadcasting allows operations between tensors of different shapes:

In [ ]:
# Broadcasting examples
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([10, 20, 30])

print("Tensor a (2x3):")
print(a)
print("\nTensor b (3,):")
print(b)

# Broadcasting: b is automatically expanded to match a's shape
result = a + b
print("\nBroadcasted addition (a + b):")
print(result)

# Broadcasting with column vector
c = torch.tensor([[100], [200]])
print("\nTensor c (2x1):")
print(c)

result2 = a + c
print("\nBroadcasted addition (a + c):")
print(result2)

# Scalar broadcasting
result3 = a * 10
print("\nScalar broadcasting (a * 10):")
print(result3)

---
<a name='6'></a>
## **6. Tensor Manipulation (Reshaping)**

### Reshaping Tensors

In [7]:
# Create a sample tensor
tensor = torch.arange(12)
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
tensor.shape

torch.Size([12])

In [9]:
# torch.reshape() - can return a copy or a view
reshaped1 = torch.reshape(tensor, (3, 4))
reshaped1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
reshaped1.shape

torch.Size([3, 4])

In [11]:
# .view() - returns a view (must be contiguous)
viewed = tensor.view(4, 3)
viewed

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [12]:
viewed.shape

torch.Size([4, 3])

**Difference Between `.view()` and `.reshape()` (Explained Simply)**

<div align="center">
  <img src="https://i.sstatic.net/ee7Hj.png" width="500"/>
  <p><i>Tensor and its underlying storage</i></p>
</div>

<div align="center">
  <img src="https://i.sstatic.net/26Q9g.png" width="500"/>
  <p><i>The right-hand tensor (shape (3,2)) can be computed from the left-hand one with t2 = t1.view(3,2)</i></p>
</div>

**What is `.view()`?**
- `.view()` changes the shape of a tensor **without copying the data**.
- It only works if the tensor's data is stored in a **contiguous block** in memory (all elements are lined up in order).
- If the tensor is **not contiguous** (for example, after a transpose), `.view()` will give an error.

**What is `.reshape()`?**
- `.reshape()` also changes the shape of a tensor.
- If possible, it returns a **view** (no copy, just like `.view()`).
- If the tensor is **not contiguous**, `.reshape()` will **make a copy** of the data so it can still give you the new shape.
- So, `.reshape()` is more flexible and works in more situations.

**What does "contiguous" mean?**
- **Contiguous**: All the elements of the tensor are stored in memory one after another, in the order you see them.
- **Non-contiguous**: The elements are not stored in order (for example, after you transpose a tensor, the way data is stored in memory changes).

**When to use `.view()`?**
- Use `.view()` when you are sure your tensor is **contiguous** (hasn't been transposed or sliced in a way that changes memory order).
- It's a bit faster because it never copies data.

**When to use `.reshape()`?**
- Use `.reshape()` if you are **not sure** if your tensor is contiguous.
- It will work in more cases, but might copy data if needed.

In [51]:
x = torch.arange(6).view(2, 3)
print(f"Original x:\n{x}")
print(f"Is x contiguous? {x.is_contiguous()}") # True

# 2. Transpose the tensor
# Memory still looks like: [0, 1, 2, 3, 4, 5]
# But the "instructions" say to read it vertically.
xt = x.transpose(0, 1)
print(f"\nTransposed x:\n{xt}")
print(f"Is transposed contiguous? {xt.is_contiguous()}") # False

# 3. Try to use .view()
try:
    print("\nAttempting xt.view(6)...")
    xt.view(6)
except RuntimeError as e:
    print(f"Error: {e}")

# 4. Make it contiguous and then use .view()
print("\nMaking xt contiguous and then viewing...")
xt_contiguous = xt.contiguous()
xt_contiguous.view(6)

Original x:
tensor([[0, 1, 2],
        [3, 4, 5]])
Is x contiguous? True

Transposed x:
tensor([[0, 3],
        [1, 4],
        [2, 5]])
Is transposed contiguous? False

Attempting xt.view(6)...
Error: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

Making xt contiguous and then viewing...


tensor([0, 3, 1, 4, 2, 5])

In [15]:
# Using -1 to infer dimension
auto_reshape = tensor.view(3, -1)
auto_reshape

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Changing Dimensions

In [17]:
# torch.squeeze() - remove dimensions of size 1
tensor_4d = torch.randn(1, 3, 1, 4)
tensor_4d

tensor([[[[ 0.2423, -1.6811,  0.0700, -1.1526]],

         [[-0.3222,  0.5486,  1.5061, -0.8805]],

         [[ 0.1760,  0.7252, -0.1779, -0.3199]]]])

In [18]:
tensor_4d.shape

torch.Size([1, 3, 1, 4])

In [19]:
squeezed = torch.squeeze(tensor_4d)
squeezed

tensor([[ 0.2423, -1.6811,  0.0700, -1.1526],
        [-0.3222,  0.5486,  1.5061, -0.8805],
        [ 0.1760,  0.7252, -0.1779, -0.3199]])

In [20]:
squeezed.shape

torch.Size([3, 4])

In [21]:
# Squeeze specific dimension
squeezed_dim = torch.squeeze(tensor_4d, dim = 0)
squeezed_dim.shape

torch.Size([3, 1, 4])

In [24]:
# torch.unsqueeze() - add a dimension of size 1
unsqueezed_0 = torch.unsqueeze(squeezed_dim, dim = 0)
unsqueezed_0.shape

torch.Size([1, 3, 1, 4])

In [25]:
# torch.unsqueeze() - add a dimension of size 1
unsqueezed_0 = torch.unsqueeze(squeezed_dim, dim = 1)
unsqueezed_0.shape

torch.Size([3, 1, 1, 4])

### Combining Tensors

In [27]:
# torch.cat() - concatenate along an existing dimension
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)

Tensor a:
tensor([[1, 2],
        [3, 4]])

Tensor b:
tensor([[5, 6],
        [7, 8]])


In [28]:
# Concatenate along dimension 0 (rows)
cat_dim0 = torch.cat([a, b], dim=0)
cat_dim0

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [29]:
# Concatenate along dimension 1 (columns)
cat_dim1 = torch.cat([a, b], dim=1)
cat_dim1

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [36]:
# torch.stack() - stack along a new dimension
stacked_dim0 = torch.stack([a, b], dim = 1) # 0 means row wise stacking and 1 means column wise stacking
stacked_dim0

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])

### Splitting Tensors

In [38]:
# Create a tensor to split
tensor = torch.arange(12).reshape(3, 4)
tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [39]:
tensor.shape

torch.Size([3, 4])

In [43]:
# torch.split() - split into chunks of a given size
splits = torch.split(tensor, 2, dim=0)
splits

(tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 tensor([[ 8,  9, 10, 11]]))

In [44]:
# torch.chunk() - split into a specific number of chunks
chunks = torch.chunk(tensor, 2, dim=1)
chunks

(tensor([[0, 1],
         [4, 5],
         [8, 9]]),
 tensor([[ 2,  3],
         [ 6,  7],
         [10, 11]]))

### Reordering Dimensions

| Operation         | Resulting Tensor                | Logic/Explanation                                      |
|-------------------|---------------------------------|--------------------------------------------------------|
| **Original**      | <pre>[[1, 2, 3],<br> [4, 5, 6]]</pre> <br>Shape: (2, 3) | Starting tensor                                        |
| `reshape(3, 2)`   | <pre>[[1, 2],<br> [3, 4],<br> [5, 6]]</pre> | Fills the new shape sequentially: 1, 2, then 3, 4, etc.|
| `permute(1, 0)`   | <pre>[[1, 4],<br> [2, 5],<br> [3, 6]]</pre> | Swaps axes: Row 1 becomes Column 1, etc.               |

**Key Difference:**
- `reshape` changes the shape by reordering the elements in memory sequentially.
- `permute` changes the order of axes (dimensions) without changing the order of elements in memory.

In [52]:
tensor = torch.randn(2,3)
tensor.shape

torch.Size([2, 3])

In [55]:
tensor

tensor([[ 1.4844,  0.0816, -0.4064],
        [ 1.4538, -0.8095, -0.0257]])

In [53]:
# Permute dimensions works by reordering the dimensions of a tensor to a specified order.
permuted = tensor.permute(1, 0)
permuted.shape

torch.Size([3, 2])

In [54]:
permuted

tensor([[ 1.4844,  1.4538],
        [ 0.0816, -0.8095],
        [-0.4064, -0.0257]])

In [ ]:
reshaped = tensor.reshape(3, 2)
reshaped.shape

torch.Size([3, 2])

In [58]:
reshaped

tensor([[ 1.4844,  0.0816],
        [-0.4064,  1.4538],
        [-0.8095, -0.0257]])

---
<a name='7'></a>
## **7. NumPy & GPU Interaction**

### NumPy Bridge

In [ ]:
# CPU Tensors and NumPy arrays share memory
np_array = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print("Original NumPy array:", np_array)

# Convert NumPy to Tensor (shares memory)
tensor_from_np = torch.from_numpy(np_array)
print("Tensor from NumPy:", tensor_from_np)

# Modify the tensor
tensor_from_np[0] = 100
print("\nAfter modifying tensor:")
print("Tensor:", tensor_from_np)
print("NumPy array (also changed!):", np_array)

# Convert Tensor to NumPy (only works on CPU tensors)
torch_tensor = torch.tensor([10.0, 20.0, 30.0, 40.0])
np_from_tensor = torch_tensor.numpy()
print("\nTensor:", torch_tensor)
print("NumPy from tensor:", np_from_tensor)

# Modify NumPy array
np_from_tensor[0] = 999
print("\nAfter modifying NumPy array:")
print("NumPy array:", np_from_tensor)
print("Tensor (also changed!):", torch_tensor)

print("\n⚠️ Note: CPU Tensors and NumPy arrays share the same memory location!")

### Moving Tensors Between CPU and GPU

In [ ]:
# Create a CPU tensor
cpu_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0])
print("CPU Tensor:", cpu_tensor)
print("Device:", cpu_tensor.device)

# Move to GPU (if available)
if torch.cuda.is_available():
    # Method 1: Using .to(device)
    gpu_tensor = cpu_tensor.to(device)
    print("\nGPU Tensor (using .to()):", gpu_tensor)
    print("Device:", gpu_tensor.device)

    # Method 2: Using .cuda()
    gpu_tensor2 = cpu_tensor.cuda()
    print("\nGPU Tensor (using .cuda()):", gpu_tensor2)
    print("Device:", gpu_tensor2.device)

    # Move back to CPU
    back_to_cpu = gpu_tensor.cpu()
    print("\nBack to CPU:", back_to_cpu)
    print("Device:", back_to_cpu.device)

    # Convert GPU tensor to NumPy (requires moving to CPU first)
    # gpu_tensor.numpy()  # This would raise an error!
    np_array = gpu_tensor.cpu().numpy()
    print("\nNumPy array from GPU tensor:", np_array)
else:
    print("\n⚠️ CUDA not available. Tensor remains on CPU.")
    print("To use GPU features, ensure you have:")
    print("1. A CUDA-capable GPU")
    print("2. CUDA toolkit installed")
    print("3. PyTorch with CUDA support installed")

---
<a name='8'></a>
## **8. NumPy vs PyTorch: Comparison and Benefits**

### Key Similarities

In [ ]:
# Similar operations in NumPy and PyTorch
print("=" * 60)
print("NUMPY vs PYTORCH - Similar Syntax")
print("=" * 60)

# Creating arrays/tensors
np_arr = np.array([1, 2, 3, 4, 5])
torch_tensor = torch.tensor([1, 2, 3, 4, 5])

print("\nNumPy array:", np_arr)
print("PyTorch tensor:", torch_tensor)

# Zeros
np_zeros = np.zeros((3, 3))
torch_zeros = torch.zeros(3, 3)
print("\nNumPy zeros:\n", np_zeros)
print("PyTorch zeros:\n", torch_zeros)

# Random values
np_rand = np.random.randn(2, 3)
torch_rand = torch.randn(2, 3)
print("\nNumPy random:\n", np_rand)
print("PyTorch random:\n", torch_rand)

# Reshaping
np_reshaped = np_arr.reshape(5, 1)
torch_reshaped = torch_tensor.reshape(5, 1)
print("\nNumPy reshaped:\n", np_reshaped)
print("PyTorch reshaped:\n", torch_reshaped)

# Mathematical operations
print("\nNumPy mean:", np_arr.mean())
print("PyTorch mean:", torch_tensor.float().mean())

print("\nNumPy sum:", np_arr.sum())
print("PyTorch sum:", torch_tensor.sum())

### Why PyTorch for Machine Learning? Key Benefits

PyTorch offers several advantages over NumPy for machine learning tasks:

#### 1. **GPU Acceleration**
- PyTorch tensors can seamlessly move between CPU and GPU
- Massive speedup for large-scale computations (10-100x faster)
- Essential for training deep neural networks

#### 2. **Automatic Differentiation (Autograd)**
- Automatically computes gradients for backpropagation
- Critical for training neural networks
- No need to manually derive and implement gradient calculations

#### 3. **Built for Deep Learning**
- Rich ecosystem of neural network layers, optimizers, and loss functions
- Easy model building with `torch.nn` module
- Pre-trained models and transfer learning support

#### 4. **Dynamic Computation Graphs**
- Graphs are built on-the-fly, allowing for flexible architectures
- Easier debugging compared to static graphs
- Supports variable-length inputs and conditional logic

#### 5. **Production Ready**
- TorchScript for model deployment
- ONNX support for interoperability
- Mobile deployment with PyTorch Mobile

#### 6. **Strong Community and Ecosystem**
- Extensive libraries (torchvision, torchaudio, etc.)
- Active research community
- Excellent documentation and tutorials

### Demonstration: GPU Speedup

In [ ]:
import time

# Large matrix multiplication comparison
size = 5000

# NumPy (CPU only)
np_a = np.random.randn(size, size)
np_b = np.random.randn(size, size)

start = time.time()
np_result = np.dot(np_a, np_b)
np_time = time.time() - start

print(f"NumPy (CPU) time: {np_time:.4f} seconds")

# PyTorch CPU
torch_a_cpu = torch.randn(size, size)
torch_b_cpu = torch.randn(size, size)

start = time.time()
torch_result_cpu = torch.matmul(torch_a_cpu, torch_b_cpu)
torch_cpu_time = time.time() - start

print(f"PyTorch (CPU) time: {torch_cpu_time:.4f} seconds")

# PyTorch GPU (if available)
if torch.cuda.is_available():
    torch_a_gpu = torch.randn(size, size).to(device)
    torch_b_gpu = torch.randn(size, size).to(device)

    # Warm up GPU
    _ = torch.matmul(torch_a_gpu, torch_b_gpu)
    torch.cuda.synchronize()

    start = time.time()
    torch_result_gpu = torch.matmul(torch_a_gpu, torch_b_gpu)
    torch.cuda.synchronize()
    torch_gpu_time = time.time() - start

    print(f"PyTorch (GPU) time: {torch_gpu_time:.4f} seconds")
    print(f"\n🚀 GPU Speedup: {torch_cpu_time / torch_gpu_time:.2f}x faster than CPU")
else:
    print("\n⚠️ GPU not available for speed comparison")

### Demonstration: Automatic Differentiation (Autograd)
This is PyTorch's killer feature for machine learning!

In [ ]:
# Automatic differentiation example
# Enable gradient tracking with requires_grad=True
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# Define a computation
z = x**2 + y**3
print(f"x = {x.item()}")
print(f"y = {y.item()}")
print(f"z = x² + y³ = {z.item()}")

# Compute gradients automatically
z.backward()

# Access gradients
print(f"\n∂z/∂x = 2x = {x.grad.item()}")  # Should be 2*x = 4
print(f"∂z/∂y = 3y² = {y.grad.item()}")  # Should be 3*y² = 27

print("\n✨ PyTorch automatically computed these gradients!")
print("This is essential for training neural networks with backpropagation.")

# NumPy cannot do this - you'd have to compute gradients manually
print("\n⚠️ NumPy doesn't have automatic differentiation.")
print("You would need to manually derive and implement gradient calculations.")

### Summary Comparison Table

| Feature | NumPy | PyTorch |
|---------|-------|---------|
| **Data Structure** | ndarray | Tensor |
| **GPU Support** | ❌ No | ✅ Yes |
| **Automatic Differentiation** | ❌ No | ✅ Yes (Autograd) |
| **Deep Learning** | ❌ Not built for it | ✅ Purpose-built |
| **Speed (CPU)** | Very fast | Very fast |
| **Speed (GPU)** | N/A | 10-100x faster |
| **Use Case** | General numerical computing | Machine Learning & DL |
| **Syntax** | Similar | Similar to NumPy |
| **Ecosystem** | SciPy, scikit-learn | torchvision, torchaudio |
| **Learning Curve** | Moderate | Easy if you know NumPy |

### When to Use What?

**Use NumPy when:**
- Doing general numerical computations
- Working with small to medium datasets
- Not training neural networks
- CPU processing is sufficient

**Use PyTorch when:**
- Building and training neural networks
- Need GPU acceleration
- Require automatic differentiation
- Working on deep learning projects
- Need production deployment of ML models

## Conclusion

In this tutorial, you've learned:

1. ✅ What PyTorch is and why it's essential for deep learning
2. ✅ How to create tensors in various ways
3. ✅ Tensor attributes and properties
4. ✅ Indexing, slicing, and filtering tensors
5. ✅ Essential tensor operations (arithmetic, matrix ops, reductions)
6. ✅ Tensor manipulation (reshaping, combining, splitting)
7. ✅ NumPy integration and GPU acceleration
8. ✅ Key differences between NumPy and PyTorch
9. ✅ Why PyTorch is superior for machine learning

### Next Steps

- Explore PyTorch's autograd in depth
- Learn about `torch.nn` for building neural networks
- Practice with real datasets using `torch.utils.data`
- Implement your first neural network!

**Happy Learning! 🚀**