In [ ]:
# @title
from IPython.display import display, HTML

display(HTML("""
<script>
const firstCell = document.querySelector('.cell.code_cell');
if (firstCell) {
  firstCell.querySelector('.input').style.pointerEvents = 'none';
  firstCell.querySelector('.input').style.opacity = '0.5';
}
</script>
"""))

html = """
<div style="display:flex; flex-direction:column; align-items:center; text-align:center; gap:12px; padding:8px;">
  <h1 style="margin:0;">👋 Welcome to <span style="color:#1E88E5;">Algopath Coding Academy</span>!</h1>

  <img src="https://raw.githubusercontent.com/sshariqali/mnist_pretrained_model/main/algopath_logo.jpg"
       alt="Algopath Coding Academy Logo"
       width="400"
       style="border-radius:15px; box-shadow:0 4px 12px rgba(0,0,0,0.2); max-width:100%; height:auto;" />

  <p style="font-size:16px; margin:0;">
    <em>Empowering young minds to think creatively, code intelligently, and build the future with AI.</em>
  </p>
</div>
"""

display(HTML(html))

# PyTorch Tensors Tutorial


**Table of Contents:**
1. [Introduction to PyTorch](#1)
2. [Creating Tensors](#2)
3. [Tensor Attributes and Properties](#3)
4. [Tensor Indexing Slicing and Filtering](#4)
5. [Tensor Operations](#5)
6. [Tensor Manipulation](#6)
7. [GPU Interaction](#7)
8. [NumPy vs PyTorch Comparison](#8)

---

<a name='1'></a>
## **1. Introduction to PyTorch Tensors**

### What is PyTorch?
PyTorch is an open-source deep learning library developed by Facebook's AI Research lab. It provides:
- Tensor computation with strong GPU acceleration
- Automatic differentiation for building neural networks
- A flexible and intuitive API for research and production

### What is a Tensor?
A **tensor** is the core data structure in PyTorch. Think of it as:
- Similar to a NumPy `ndarray` but with additional capabilities
- Can run on GPUs for accelerated computing
- Supports automatic differentiation (autograd) for neural network training
- A multi-dimensional array that can represent scalars, vectors, matrices, and higher-dimensional data

### Importing PyTorch

In [21]:
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")

PyTorch version: 2.9.1+cpu


### Setting up your Device
Check if CUDA (GPU) is available and set the device accordingly:

In [22]:
# Check if CUDA is available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

if device == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available, using CPU")

Using device: cpu
GPU not available, using CPU


---
<a name='2'></a>
## **2. Creating Tensors**

### From Existing Data

In [23]:
# Using torch.tensor() - from Python lists or tuples
tensor_1d = torch.tensor([9, 12, 25, 5, 10])
tensor_1d

tensor([ 9, 12, 25,  5, 10])

In [24]:
# 2D tensor from nested list
tensor_2d = torch.tensor([[9, 12, 25], [5, 10, 16]])
tensor_2d

tensor([[ 9, 12, 25],
        [ 5, 10, 16]])

In [25]:
# Using torch.from_numpy() - from NumPy array
np_array = np.array([12, 15, 20, 25])
tensor_from_numpy = torch.from_numpy(np_array)
tensor_from_numpy

tensor([12, 15, 20, 25])

### Creating New Tensors

In [26]:
# torch.zeros()
zeros_tensor = torch.zeros(3, 4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# torch.ones()
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
# torch.rand() - uniform distribution [0, 1)
# random values between 0 and 1. Uniform distribution means all values are equally likely.
rand_uniform = torch.rand(3, 3)
rand_uniform

tensor([[0.0664, 0.1018, 0.5533],
        [0.7426, 0.2093, 0.7567],
        [0.7145, 0.8365, 0.5752]])

In [29]:
# torch.arange() - sequence of values
arange_tensor = torch.arange(0, 10, 2)
arange_tensor

tensor([0, 2, 4, 6, 8])

---
<a name='3'></a>
## **3. Tensor Attributes and Properties**

In [31]:
# Create a sample tensor
sample_tensor = torch.rand(2, 3)
sample_tensor

tensor([[0.6774, 0.1257, 0.0521],
        [0.7637, 0.2455, 0.7043]])

In [32]:
# Data type
sample_tensor.dtype

torch.float32

In [33]:
# Shape
sample_tensor.shape # sample_tensor.size()

torch.Size([2, 3])

In [34]:
# Check which device the tensor is on
print(sample_tensor.device)

# Move tensor to GPU if available
if torch.cuda.is_available():
    sample_tensor = sample_tensor.to('cuda')
    print(sample_tensor.device)

cpu


In [35]:
# Number of dimensions
sample_tensor.ndim

2

In [36]:
# Total number of elements
sample_tensor.numel()

6

In [37]:
# Create tensors with specific dtypes
int_tensor = torch.tensor([1, 2, 3], dtype = torch.long)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype = torch.float32)
print(f"Integer tensor dtype: {int_tensor.dtype}")
print(f"Float tensor dtype: {float_tensor.dtype}")

Integer tensor dtype: torch.int64
Float tensor dtype: torch.float32


---
<a name='4'></a>
## **4. Tensor Indexing, Slicing, and Filtering**

In [38]:
# Create a sample tensor for indexing
tensor = torch.rand(4,6)
tensor

tensor([[0.9331, 0.6773, 0.4257, 0.3674, 0.4492, 0.2314],
        [0.4501, 0.4761, 0.1579, 0.5700, 0.2652, 0.7457],
        [0.0918, 0.8349, 0.4894, 0.7036, 0.5727, 0.9568],
        [0.8287, 0.4557, 0.0399, 0.1880, 0.2801, 0.4225]])

In [39]:
# Standard indexing
tensor[0, 0] # Access element at row 0, column 0

tensor(0.9331)

In [40]:
# Accessing rows and columns
tensor[0] # First row
# tensor[:, 1] # Second column

tensor([0.9331, 0.6773, 0.4257, 0.3674, 0.4492, 0.2314])

In [41]:
# Slicing
tensor[0:2] # First 2 rows

tensor([[0.9331, 0.6773, 0.4257, 0.3674, 0.4492, 0.2314],
        [0.4501, 0.4761, 0.1579, 0.5700, 0.2652, 0.7457]])

In [42]:
tensor[1:3, 2:4] # Rows 1-3, Columns 2-4

tensor([[0.1579, 0.5700],
        [0.4894, 0.7036]])

In [45]:
# Boolean/Masked indexing
mask = tensor > 0.5
print("Boolean mask (elements > 0.5):") # 
print(mask) # boolean mask retains the original tensor's shape
print("\nFiltered values (> 0.5):")
print(tensor[mask]) # filtered values are a 1D array of only the elements that meet the condition.

Boolean mask (elements > 10):
tensor([[ True,  True, False, False, False, False],
        [False, False, False,  True, False,  True],
        [False,  True, False,  True,  True,  True],
        [ True, False, False, False, False, False]])

Filtered values (> 10):
tensor([0.9331, 0.6773, 0.5700, 0.7457, 0.8349, 0.7036, 0.5727, 0.9568, 0.8287])


In [47]:
# torch.where() - conditional selection
result = torch.where(tensor > 0.5, tensor, torch.tensor(0)) # replace values <= 0.5 with 0
result

tensor([[0.9331, 0.6773, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5700, 0.0000, 0.7457],
        [0.0000, 0.8349, 0.0000, 0.7036, 0.5727, 0.9568],
        [0.8287, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

---
<a name='5'></a>
## **5. Tensor Operations**

### Element-wise Arithmetic

In [52]:
# Create sample tensors
a = torch.rand((3,2))
b = torch.rand((3,2))

print("Tensor a:\n", a)
print("Tensor b:\n", b)

Tensor a:
 tensor([[0.6581, 0.5738],
        [0.1634, 0.5728],
        [0.1141, 0.6779]])
Tensor b:
 tensor([[0.4400, 0.3766],
        [0.5407, 0.9020],
        [0.2807, 0.2133]])


In [53]:
# Addition
a + b # or torch.add(a, b)

tensor([[1.0981, 0.9504],
        [0.7041, 1.4748],
        [0.3948, 0.8912]])

In [54]:
# Subtraction
a - b # or torch.sub(a, b)

tensor([[ 0.2181,  0.1973],
        [-0.3773, -0.3292],
        [-0.1666,  0.4645]])

In [55]:
# Multiplication (element-wise)
a * b # or torch.mul(a, b)

tensor([[0.2896, 0.2161],
        [0.0883, 0.5167],
        [0.0320, 0.1446]])

In [56]:
# Division
a / b # or torch.div(a, b)

tensor([[1.4957, 1.5239],
        [0.3022, 0.6350],
        [0.4064, 3.1772]])

In [57]:
# Power
a ** 2 # or torch.pow(a, 2)

tensor([[0.4331, 0.3293],
        [0.0267, 0.3281],
        [0.0130, 0.4595]])

In [58]:
# Scalar operations
scalar = 2.0
a + scalar

tensor([[2.6581, 2.5738],
        [2.1634, 2.5728],
        [2.1141, 2.6779]])

### Matrix Operations

In [64]:
# Matrix multiplication
mat1 = torch.tensor([[10, 6], [25, 13]])
mat2 = torch.tensor([[19, 45], [16, 2]])

print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)

Matrix 1:
 tensor([[10,  6],
        [25, 13]])
Matrix 2:
 tensor([[19, 45],
        [16,  2]])


In [65]:
# Matrix multiplication using torch.matmul()
result1 = torch.matmul(mat1, mat2)
result1

tensor([[ 286,  462],
        [ 683, 1151]])

In [66]:
# Matrix multiplication using @ operator
result2 = mat1 @ mat2
result2

tensor([[ 286,  462],
        [ 683, 1151]])

In [67]:
# Transpose
mat1.transpose(0, 1)  # Swap dimensions 0 and 1 
# torch.transpose(mat, 0, 1)  # Alternative method

tensor([[10, 25],
        [ 6, 13]])

In [69]:
mat1.T # Shortcut for transpose for 2D tensors

tensor([[10, 25],
        [ 6, 13]])

### Reduction Operations

In [71]:
# Create a sample tensor
tensor = torch.tensor([[10, 6, 25],
                       [13, 19, 45],
                       [16, 2, 11]], dtype=torch.float)
tensor

tensor([[10.,  6., 25.],
        [13., 19., 45.],
        [16.,  2., 11.]])

In [72]:
# Sum
torch.sum(tensor)
torch.sum(tensor, dim = 0) # Sum along columns
torch.sum(tensor, dim = 1) # Sum along rows

tensor([41., 77., 29.])

In [74]:
# Mean
torch.mean(tensor)
torch.mean(tensor, dim=0)

tensor([13.,  9., 27.])

In [75]:
# Standard deviation
torch.std(tensor, dim=1)

tensor([10.0167, 17.0098,  7.0946])

In [76]:
# Max and Min
torch.max(tensor) # along dimension can be specified as well by torch.max(tensor, dim=0)
torch.min(tensor) # along dimension can be specified as well by torch.min(tensor, dim=0)

tensor(2.)

In [77]:
# Argmax (index of maximum value)
torch.argmax(tensor)
torch.argmax(tensor, dim=0)
torch.argmax(tensor, dim=1)

tensor([2, 2, 0])

### Broadcasting
Broadcasting allows operations between tensors of different shapes:

In [78]:
# Broadcasting examples
a = torch.tensor([[10, 6, 25],
                  [13, 19, 45]])
b = torch.tensor([16, 12, 11])

print("Tensor a:")
print(a)
print(a.shape)
print("\nTensor b:")
print(b)
print(b.shape)

Tensor a:
tensor([[10,  6, 25],
        [13, 19, 45]])
torch.Size([2, 3])

Tensor b:
tensor([16, 12, 11])
torch.Size([3])


In [79]:
# Broadcasting: b is automatically expanded to match a's shape
result = a + b
print("\nBroadcasted addition (a + b):")
print(result)


Broadcasted addition (a + b):
tensor([[26, 18, 36],
        [29, 31, 56]])


---
<a name='6'></a>
## **6. Tensor Manipulation (Reshaping)**

### Reshaping Tensors

In [80]:
# Create a sample tensor
tensor = torch.arange(11, 23)
tensor

tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [81]:
tensor.shape

torch.Size([12])

In [82]:
# Reshaping to (3, 4)
reshaped_tensor = torch.reshape(tensor, (3, 4))
reshaped_tensor

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]])

In [83]:
reshaped_tensor.shape

torch.Size([3, 4])

In [84]:
# .view() - returns a view
viewed = tensor.view(3, 4)
viewed

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]])

In [86]:
viewed.shape

torch.Size([3, 4])

Difference between .view() and .reshape()

In [87]:
x = torch.tensor([[5,7],[1,3],[6,8]])
x

tensor([[5, 7],
        [1, 3],
        [6, 8]])

In [88]:
x_t = x.transpose(0, 1)
x_t

tensor([[5, 1, 6],
        [7, 3, 8]])

In [89]:
x_t.view(3,2)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [90]:
x_t.reshape(3,2)

tensor([[5, 1],
        [6, 7],
        [3, 8]])

In [91]:
# Using -1 to infer dimension
auto_reshape = tensor.view(3, -1)
auto_reshape

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]])

### Changing Dimensions

In [92]:
# torch.squeeze() - remove dimensions of size 1
tensor_4d = torch.rand(1, 3, 1, 4)
tensor_4d

tensor([[[[0.6979, 0.7816, 0.6311, 0.4191]],

         [[0.6843, 0.9599, 0.9263, 0.4475]],

         [[0.3459, 0.3946, 0.7296, 0.3074]]]])

In [93]:
tensor_4d.shape

torch.Size([1, 3, 1, 4])

In [94]:
squeezed = torch.squeeze(tensor_4d)
squeezed

tensor([[0.6979, 0.7816, 0.6311, 0.4191],
        [0.6843, 0.9599, 0.9263, 0.4475],
        [0.3459, 0.3946, 0.7296, 0.3074]])

In [95]:
squeezed.shape

torch.Size([3, 4])

In [96]:
# Squeeze specific dimension
squeezed_dim = torch.squeeze(tensor_4d, dim = 0)
squeezed_dim.shape

torch.Size([3, 1, 4])

In [97]:
# torch.unsqueeze() - add a dimension of size 1
unsqueezed_0 = torch.unsqueeze(squeezed_dim, dim = 0)
unsqueezed_0.shape

torch.Size([1, 3, 1, 4])

In [98]:
# torch.unsqueeze() - add a dimension of size 1
unsqueezed_0 = torch.unsqueeze(squeezed_dim, dim = 1)
unsqueezed_0.shape

torch.Size([3, 1, 1, 4])

### Combining Tensors

In [99]:
a = torch.tensor([[10, 6], [25, 13]])
b = torch.tensor([[9, 45], [17, 26]])

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)

Tensor a:
tensor([[10,  6],
        [25, 13]])

Tensor b:
tensor([[ 9, 45],
        [17, 26]])


In [100]:
# Concatenate along dimension 0 (rows)
cat_dim0 = torch.cat([a, b], dim=0)
cat_dim0

tensor([[10,  6],
        [25, 13],
        [ 9, 45],
        [17, 26]])

In [102]:
# Concatenate along dimension 1 (columns)
cat_dim1 = torch.cat([a, b], dim=1)
cat_dim1

tensor([[10,  6,  9, 45],
        [25, 13, 17, 26]])

### Splitting Tensors

In [107]:
# Create a tensor to split
tensor = torch.rand(3, 4)
tensor

tensor([[0.4658, 0.1350, 0.5459, 0.8956],
        [0.1447, 0.4234, 0.4259, 0.0410],
        [0.6710, 0.6812, 0.5658, 0.6286]])

In [108]:
tensor.shape

torch.Size([3, 4])

In [109]:
# torch.split() - split into chunks of a given size
splits = torch.split(tensor, 2, dim=0)
splits

(tensor([[0.4658, 0.1350, 0.5459, 0.8956],
         [0.1447, 0.4234, 0.4259, 0.0410]]),
 tensor([[0.6710, 0.6812, 0.5658, 0.6286]]))

In [110]:
# torch.chunk() - split into a specific number of chunks
chunks = torch.chunk(tensor, 2, dim=1)
chunks

(tensor([[0.4658, 0.1350],
         [0.1447, 0.4234],
         [0.6710, 0.6812]]),
 tensor([[0.5459, 0.8956],
         [0.4259, 0.0410],
         [0.5658, 0.6286]]))

---
<a name='7'></a>
## **7. NumPy & GPU Interaction**

### Moving Tensors Between CPU and GPU

In [ ]:
# Create a CPU tensor
cpu_tensor = torch.tensor([26.0, 12.0, 31.0, 42.0])
print("CPU Tensor:", cpu_tensor)
print("Device:", cpu_tensor.device)

In [ ]:
# Create a GPU tensor (if CUDA is available)
gpu_tensor = torch.tensor([26.0, 12.0, 31.0, 42.0], device = 'cuda')
print("GPU Tensor:", gpu_tensor)
print("Device:", gpu_tensor.device)

### NumPy Bridge

In [ ]:
# Convert Tensor to NumPy (only works on CPU tensors)

np_from_tensor = cpu_tensor.numpy()
print("NumPy from tensor:", np_from_tensor)

---
<a name='8'></a>
## **8. Benefits of PyTorch over NumPy**

### Why PyTorch for Machine Learning? Key Benefits

PyTorch offers several advantages over NumPy for machine learning tasks:

#### 1. **GPU Acceleration**
- PyTorch tensors can seamlessly move between CPU and GPU
- Massive speedup for large-scale computations (10-100x faster)
- Essential for training deep neural networks

#### 2. **Automatic Differentiation (Autograd)**
- Automatically computes gradients for backpropagation
- Critical for training neural networks
- No need to manually derive and implement gradient calculations

#### 3. **Built for Deep Learning**
- Rich ecosystem of neural network layers, optimizers, and loss functions
- Easy model building with `torch.nn` module
- Pre-trained models and transfer learning support

#### 4. **Strong Community and Ecosystem**
- Extensive libraries (torchvision, torchaudio, etc.)
- Active research community
- Excellent documentation and tutorials

### Demonstration: GPU Speedup

In [ ]:
import time

In [ ]:
# Large matrix multiplication comparison
size = 5000

In [ ]:
# NumPy (CPU only)
np_a = np.random.randn(size, size)
np_b = np.random.randn(size, size)

In [ ]:
# PyTorch CPU
torch_a_cpu = torch.randn(size, size)
torch_b_cpu = torch.randn(size, size)

In [ ]:
# PyTorch GPU
torch_a_gpu = torch.randn(size, size).to('cuda')
torch_b_gpu = torch.randn(size, size).to('cuda')

In [ ]:
start = time.time()
np_result = np.dot(np_a, np_b)
np_time = time.time() - start

print(f"NumPy (CPU) time: {np_time:.4f} seconds")

In [ ]:
start = time.time()
torch_result_cpu = torch_a_cpu @ torch_b_cpu
torch_cpu_time = time.time() - start

print(f"PyTorch (CPU) time: {torch_cpu_time:.4f} seconds")

In [ ]:
start = time.time()
torch_result_gpu = torch_a_gpu @ torch_b_gpu
torch_gpu_time = time.time() - start

print(f"PyTorch (GPU) time: {torch_gpu_time:.4f} seconds")

In [ ]:
# # PyTorch GPU (if available)
# if torch.cuda.is_available():
#     torch_a_gpu = torch.randn(size, size).to(device)
#     torch_b_gpu = torch.randn(size, size).to(device)

#     # Warm up GPU
#     _ = torch.matmul(torch_a_gpu, torch_b_gpu)
#     torch.cuda.synchronize()

#     start = time.time()
#     torch_result_gpu = torch.matmul(torch_a_gpu, torch_b_gpu)
#     torch.cuda.synchronize()
#     torch_gpu_time = time.time() - start

#     print(f"PyTorch (GPU) time: {torch_gpu_time:.4f} seconds")
#     print(f"\n🚀 GPU Speedup: {torch_cpu_time / torch_gpu_time:.2f}x faster than CPU")
# else:
#     print("\n⚠️ GPU not available for speed comparison")

### When to Use What?

**Use NumPy when:**
- Doing general numerical computations
- Working with small to medium datasets
- Not training neural networks
- CPU processing is sufficient

**Use PyTorch when:**
- Building and training neural networks
- Need GPU acceleration
- Require automatic differentiation
- Working on deep learning projects
- Need production deployment of ML models

---
<a name='9'></a>
## **9. Reading Material**

### torch.rand() vs torch.randn()

<div align="center">
  <img src="https://i-blog.csdnimg.cn/direct/e34944beb690439b8505f2bba367b7cc.png" width="700"/>
  <p><i>Uniform Distribution vs Normal Distribution</i></p>
</div>

In [ ]:
# torch.rand() - uniform distribution [0, 1)
# random values between 0 and 1. Uniform distribution means all values are equally likely.
rand_uniform = torch.rand(3, 3)
rand_uniform

In [ ]:
# torch.randn() - standard normal distribution (mean=0, std=1)
# random values from a normal distribution with mean 0 and standard deviation 1. 
# 68.3 % probability that values are between -1 and 1
# 95.4 % probability that values are between -2 and 2
# range is theoretically from -infinity to +infinity.

rand_normal = torch.randn(3, 3)
rand_normal

### In-place Operations
Operations ending with `_` modify the tensor in-place:

In [ ]:
# In-place addition
a.add_(5)
a

In [ ]:
# In-place multiplication
a.subtract_(3)
a

# Note: In-place operations save memory but modify the original tensor
# Regular operations create new tensors

### Stacking

In [17]:
a = torch.tensor([[10, 6], [25, 13]])
b = torch.tensor([[9, 45], [17, 26]])

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)

Tensor a:
tensor([[10,  6],
        [25, 13]])

Tensor b:
tensor([[ 9, 45],
        [17, 26]])


In [ ]:
# torch.stack() - stack along a new dimension
stacked_dim0 = torch.stack([a, b], dim = 0) # 0 means row wise stacking and 1 means column wise stacking
stacked_dim0

In [ ]:
stacked_dim0.shape

### Reordering Dimensions

| Operation         | Resulting Tensor                | Logic/Explanation                                      |
|-------------------|---------------------------------|--------------------------------------------------------|
| **Original**      | <pre>[[1, 2, 3],<br> [4, 5, 6]]</pre> <br>Shape: (2, 3) | Starting tensor                                        |
| `reshape(3, 2)`   | <pre>[[1, 2],<br> [3, 4],<br> [5, 6]]</pre> | Fills the new shape sequentially: 1, 2, then 3, 4, etc.|
| `permute(1, 0)`   | <pre>[[1, 4],<br> [2, 5],<br> [3, 6]]</pre> | Swaps axes: Row 1 becomes Column 1, etc.               |

**Key Difference:**
- `reshape` changes the shape by reordering the elements in memory sequentially.
- `permute` changes the order of axes (dimensions) without changing the order of elements in memory.
- `permute` serves a similar purpose to `transpose`, but while `transpose` swaps exactly two dimensions, `permute` can rearrange all dimensions in any order you like.

In [18]:
tensor = torch.rand(2,3)
print(tensor.shape)
tensor

torch.Size([2, 3])


tensor([[0.9962, 0.2111, 0.3090],
        [0.3452, 0.8704, 0.6638]])

In [20]:
# Permute dimensions works by reordering the dimensions of a tensor to a specified order.
permuted = tensor.permute(1, 0)
print(permuted.shape)
permuted

torch.Size([3, 2])


tensor([[0.9962, 0.3452],
        [0.2111, 0.8704],
        [0.3090, 0.6638]])

---
<a name='10'></a>
## **10. Practice Exercises**

Test your understanding of PyTorch tensors with these hands-on exercises!

### Exercise 1: Creating Tensors
Create a 4x5 tensor filled with random values from a normal distribution (mean=0, std=1). Then convert it to a tensor with dtype `torch.float64`.

In [111]:
# Your code here

### Exercise 2: Challenge - Normalize a Tensor
Create a tensor of shape (5, 6) with random values from a uniform distribution. Normalize it so that each column has mean 0 and standard deviation 1. (Hint: Use broadcasting and reduction operations)

In [112]:
# Your code here

### Exercise 3: NumPy Integration
Create a NumPy array with shape (4, 4) containing random integers between 1 and 100. Convert it to a PyTorch tensor, compute the sum of each row, then convert the result back to a NumPy array.

In [113]:
# Your code here

### Exercise 4: Combining Tensors
Create three tensors of shape (2, 3). Stack them along a new dimension (dim=0), then concatenate them along dimension 1 instead.

In [114]:
# Your code here

### Exercise 5: Reshaping
Create a 1D tensor with values from 0 to 23. Reshape it to (2, 3, 4). Then use `permute` to swap the first and last dimensions.

In [115]:
# Your code here

### Exercise 6: Broadcasting
Create a tensor A of shape (3, 4) and a tensor B of shape (4,). Add them together using broadcasting, then verify the shape of the result.

In [116]:
# Your code here

### Exercise 7: Reduction Operations
Create a 5x5 tensor with random values. Calculate the mean of each row and the standard deviation of each column.

In [117]:
# Your code here

### Exercise 8: Matrix Operations
Create two matrices A (3x4) and B (4x5) with random values. Compute their matrix product and find the maximum value in the resulting matrix along with its index.

In [118]:
# Your code here

### Exercise 9: Boolean Masking
Create a tensor with values from 1 to 20. Use boolean masking to extract only the values that are divisible by 3.

In [119]:
# Your code here

### Exercise 10: Tensor Indexing
Create a tensor of shape (6, 8) with random values. Extract the middle 2x4 submatrix (rows 2-3, columns 2-5).

In [120]:
# Your code here

## Conclusion

In this tutorial, you've learned:

1. ✅ What PyTorch is and why it's essential for deep learning
2. ✅ How to create tensors in various ways
3. ✅ Tensor attributes and properties
4. ✅ Indexing, slicing, and filtering tensors
5. ✅ Essential tensor operations (arithmetic, matrix ops, reductions)
6. ✅ Tensor manipulation (reshaping, combining, splitting)
7. ✅ NumPy integration and GPU acceleration
8. ✅ Key differences between NumPy and PyTorch
9. ✅ Why PyTorch is superior for machine learning

### Next Steps

- Explore PyTorch's autograd in depth
- Learn about `torch.nn` for building neural networks
- Practice with real datasets using `torch.utils.data`
- Implement your first neural network!

**Happy Learning! 🚀**