In [2]:
import torch

### Self-Attention

In [11]:
torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

Language Modelling Principal (Token Communication):

Token in 5th Location for example should not be able to communicate with token in 6th, 7th or 8th token as they are future tokens. 

It should only be able to communicate with tokens before it.

We can do this using Matrix Multiplication

In [12]:
torch.manual_seed(1337)
a = torch.tril(torch.ones(3, 3)) # torch.ones(3, 3)
b = torch.randint(0, 10, (3,2), dtype = torch.float)
c = a @ b

print('a=')
print(a)
print('b=')
print(b)
print('c=')
print(c)

a=
tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
b=
tensor([[5., 7.],
        [2., 0.],
        [5., 3.]])
c=
tensor([[ 5.,  7.],
        [ 7.,  7.],
        [12., 10.]])


In [20]:
# Version 1
wei = torch.tril(torch.ones(T,T))
wei = wei / wei.sum(1, keepdim=True) # normalize the rows
out_1 = wei @ x # (T,T) @ (B,T,C) ---> (B,T,T) @ (B,T,C) ---> (B,T,C)
out_1.shape

torch.Size([4, 8, 2])

In [19]:
# Version 2
tril = torch.tril(torch.ones(T,T))
wei = torch.zeros(T,T)
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = torch.softmax(wei, dim=-1)
out_2 = wei @ x
out_2.shape

torch.Size([4, 8, 2])